### ISSUE TITLE
Enhancement in navbar

### ISSUE THREAD

**Issue by Aditi323** [Priyaaa1/StartConnect-Hub#1]
![Screenshot (351)](https://github.com/Priyaaa1/StartConnect-Hub/assets/114893448/4ac484b7-dda5-4db8-8344-fe644c86c844)
I want to add hover effect to the navbar items under GSSOC'24

**Comment by Jithendranath8** [comment]
i think i can solve this issue , please assign this issue to me

**Comment by CharanAdithya6505** [comment]
i have some good experience in enhancing nav bar i did some great projects on it, could you please assaign it me, i will do it...Thank you

**Comment by rishyym0927** [comment]
Hi @Aditi323 ,

I want to work on this issue #1, I feel that adding some elements from external library can make it wonderful.

Thank you

**Comment by Shyambarua** [comment]
Assign this issue to me.
As a full Stack Developer and 1 Year experience I can Write optimized code and Make it responsive.

**Comment by sarthak-stranger** [comment]
Hi, Can you Please Assign this issue to me , I am Experienced in Webdev, also have some interactive designs, i will improve this nav bar section according to the main theme.
