### ISSUE TITLE
Bug: every section should have atleast full viewport

### ISSUE THREAD

**Issue by Aayushraj22** [Priyaaa1/StartConnect-Hub#10]
Each navigation tab should send to the corrosponding content on clicking it and display only the related content.

Upon clicking the **About Us** tab, you should be navigated to 'About Us' section and it is doing it correctly but the problem is, it also displays some content of Home section which is not supposed to be shown in About Us section.
> Also each section should be displayed isolated from the other section [can be differentiated based on background-color] and covers atleast the full viewport [height and width].

![Screenshot (68)](https://github.com/Priyaaa1/StartConnect-Hub/assets/97510973/08d8426a-6dea-43ea-a197-417f5e39a6bd)

**Comment by cpratik1307** [comment]
Please assign me this project for GSSoC, and I will take it on.

**Comment by Aayushraj22** [comment]
Assign it to me

**Comment by prerana-jain** [comment]
@Priyaaa1, I would like to contribute here. Please assign it to me under GsSOC'24

**Comment by Yuvraj960** [comment]
@Priyaaa1 Please assign this issue to me under GSSoC24

**Comment by govindumeesala** [comment]
@Priyaaa1 I would like to contribute here. Please assign it to me.

**Comment by rahulnarayaniitk** [comment]
@Aayushraj22 I would like to work on this issue under GSSoC '24.
Please assign this issue to me.
