### ISSUE TITLE
GSSOC '24 : Add a 'Back top Top' button 

### ISSUE THREAD

**Issue by sujanrupu** [Priyaaa1/StartConnect-Hub#101]
**Is your feature request related to a problem? Please describe.**
In a single page application, to remove the hustle of repetitive scrolling I want to add a button at the bottom of the page, by clicking which user will be automatically scrolled to top of the page.

**Describe the solution you'd like**
In a single page application, to remove the hustle of repetitive scrolling I want to add a button at the bottom of the page, by clicking which user will be automatically scrolled to top of the page.

**Comment by Priyaaa1** [comment]
This issue has been resolved.
