### ISSUE TITLE
Making the Logo Clickable

### ISSUE THREAD

**Issue by Varnika2526** [Priyaaa1/StartConnect-Hub#103]
**Describe the bug**
On clicking the Logo the page should be refreshed or get to the Home Page

**To Reproduce**

**Expected behavior**
Logo should contain the link to Home Page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Varnika2526** [comment]
@Priyaaa1 Kindly assign me this issue under the GSSOC'24

**Comment by prachisah1** [comment]
@Priyaaa1 Please Assingn me this task for GSSOC 24
