### ISSUE TITLE
Adding the Social Links like LinkedIn and Github

### ISSUE THREAD

**Issue by Varnika2526** [Priyaaa1/StartConnect-Hub#108]
**Is your feature request related to a problem? Please describe.**
Adding the Social Links can be meaningful to the main topic of the Website StartConnect-Hub.
These can be added in the Footer section of the website

**Describe the solution you'd like**
Adding responsive links added to the Icons of the respective social media
@Priyaaa1 Kindly assign me this issue under GSSOC'24

**Additional context**

**Comment by prachisah1** [comment]
Please assingn me this  task for GSSOC 24

**Comment by prachisah1** [comment]
Sure thing!

Adding social media links to StartConnect-Hub's footer can really boost how people connect and engage with the site. It's all about making it easy for users to find and follow the community on platforms like Twitter, Facebook, LinkedIn, you name it. Assigning this task to @Priyaaa1 for GSSOC'24 would be a great move to get it done smoothly. With these links, visitors can seamlessly share and network, creating a more dynamic and interactive experience. It's just a simple tweak, but it can make a big difference in how people connect with StartConnect-Hub.
