### ISSUE TITLE
Not responsive 

### ISSUE THREAD

**Issue by NitinChakrawarti** [Priyaaa1/StartConnect-Hub#109]
**Describe the bug**

website losses it's responsiveness in small devices whole screen is not visible easily it is zoomed.

**To Reproduce**
open website in mobile  devices you see the error

**Expected behavior**

website content should fit viewport as we open it different devices.

**Screenshots**

![Screenshot 2024-05-13 192612](https://github.com/Priyaaa1/StartConnect-Hub/assets/149225785/cb17a205-8dba-4f84-82d7-ff162fb56c87)

![Screenshot 2024-05-13 192623](https://github.com/Priyaaa1/StartConnect-Hub/assets/149225785/5dd446bc-01cb-49aa-abf2-ebd85e8402f4)

in these screenshots you see elements are cropped.

**Additional context**

@Priyaaa1   I can fix all these issues i have good knowledge  of media queries and responsive design,
assign this issue to me under GSSoC'24

**Comment by prateeksha17** [comment]
I am interested to contribute in this section, Please assign me the issue.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
