### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Priyaaa1/StartConnect-Hub#114]
**Is your feature request related to a problem? Please describe.**
In your application anyone can enter using **temporary or disposable email**.

**Describe the solution you'd like**
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**Additional context**
Assign me this work under GSSoC24, I will implement it.

**Comment by Isha1233** [comment]
@Priyaaa1 I want to work on this issue kindly assign this issue to me
