### ISSUE TITLE
Backend Structure for the Project

### ISSUE THREAD

**Issue by soham0005** [Priyaaa1/StartConnect-Hub#115]
Heyy @Priyaaa1, may i work on the backend structure for this project? we could collaborate and have a firm backend for this under the label of gssoc

Ideas for the Backend right now:-

1) Implement Login/Signup Routes
2) Implement an API where different startups can register themselves
3) Implement APIs where Users can search and connect with the Registered Startups or firms

**Comment by SanaAzeem512** [comment]
please assign this issue to me under GSSOC24.I have done several backend project.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Isha1233** [comment]
@Priyaaa1 I want to work on this issue kindly assign this issue to me

**Comment by soham0005** [comment]
@Priyaaa1 Hey, i have some queries related to the project, got time to discuss?

**Comment by Priyaaa1** [comment]
@soham0005 any update?
