### ISSUE TITLE
[Footer]: None of these buttons are working

### ISSUE THREAD

**Issue by Karankumar2004** [Priyaaa1/StartConnect-Hub#117]
None of these buttons are working!!!
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/121598965/6075ff6d-2c9c-45dc-88cf-972a210e5e6e)
Sending to this page
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/121598965/237e61b9-0f19-41b2-a158-e877031ed14f)

Hey @Priyaaa1, I'm keen to contribute. Could you assign me this issue under GSSoc 24'?

**Comment by Isha1233** [comment]
@Priyaaa1 Kindly assign this task to me

**Comment by TitikshyaChanda** [comment]
@Priyaaa1 kindly assign me this issue

**Comment by Tejsvapandey1** [comment]
kindly assign this task to me

**Comment by n14rishitha** [comment]
Hi @Priyaaa1 
I would like to work on this issue . so please assign this task to me . I really want to contribute in this issue .
