### ISSUE TITLE
Implement backend to your project 

### ISSUE THREAD

**Issue by Vishnu1804K** [Priyaaa1/StartConnect-Hub#12]
I need to implement login and signup page into your project so that the website can be work dynamically please assign me this issue under GSSOC'24

**Comment by divyanshahlawat** [comment]
I would like to work on this feature, can you assign this issue?

**Comment by Himanshityagii24** [comment]
I went through the project and want to contribute towards the backend of this project. Can work on the backend of login and signup page and contact us section by creating  API end points for signup , login and contact us connecting them to MongoDB, designing data model , thus I can  work on the backend part of your project.

**Comment by divyanshahlawat** [comment]
It's not my project Himanshi, but I'm commenting because I'd like to
contribute to it

**Comment by Himanshityagii24** [comment]
@Vishnu1804K ,I went through the project and want to contribute towards the backend of this project. Can work on the backend of login and signup page and contact us section by creating API end points for signup , login and contact us connecting them to MongoDB, designing data model , thus I can work on the backend part of your project.

**Comment by divyanshahlawat** [comment]
I understand what are you talking about but I am not the admin of
this project and I am person like you who wants to contribute.If you want
to connect with admin you could see on top.

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24  contributer , I would like to work on this issue. Could you kindly assign me to work on this issue?

**Comment by kashish-51** [comment]
I would love to contribute to your repository by adding some backend functionality and make it better than before. So, can you please assign this to me?

**Comment by Vishnu1804K** [comment]
hey Priyaaa1 assgin this task to only me

**Comment by Himanshityagii24** [comment]
@Priyaaa1, I went through the project and want to contribute towards the backend of this project. Can work on the backend of login and signup page and contact us section by creating API end points for signup , login and contact us connecting them to MongoDB, designing data model , thus I can work on the backend part of your project.

**Comment by SanaAzeem512** [comment]
@Priyaaa1 , I would like to work on this issue. Could you kindly assign me to work on this issue under GSSOC24

**Comment by Priyaaa1** [comment]
@Vishnu1804K any update?

**Comment by Priyaaa1** [comment]
@Himanshityagii24 do you want to do this task?

**Comment by Himanshityagii24** [comment]
Yes i was busy with my end sems and intern work, i will complete it just give me some time

**Comment by Himanshityagii24** [comment]
@Priyaaa1 pls assign this task to someone else as it's not possible for me to take out time for this

**Comment by Priyaaa1** [comment]
@Himanshityagii24 okay
