### ISSUE TITLE
Adding a feature of redirecting to home page on clicking the icon.

### ISSUE THREAD

**Issue by adityakishore25** [Priyaaa1/StartConnect-Hub#122]
By clicking on an icon located on either the signup or login page redirects the user to the homepage. @Priyaaa1 could you assign me this. I want to work on this feature under GSSoC'24.

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/107037851/748d9afb-f2aa-42c8-a796-6d064d57b78b)

**Comment by Priyaaa1** [comment]
@adityakishore25 it has been implemented
