### ISSUE TITLE
Implement Dark Mode Feature 

### ISSUE THREAD

**Issue by adityakishore25** [Priyaaa1/StartConnect-Hub#123]
As a user, I would like to have the option to switch between light and dark modes on the website for improved readability and reduced eye strain, especially during low-light conditions. Implementing a dark mode feature would enhance the user experience and provide greater flexibility in customising the visual appearance of the website.
@Priyaaa1 could you assign me this issue under GSSoC'24.

**Comment by AkshatJangid787** [comment]
could you please assign me this issue?

**Comment by Madhuril-Bhaskar** [comment]
please assign this task to me

**Comment by Tejsvapandey1** [comment]
please assign this task to me

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Priyaaa1
