### ISSUE TITLE
Updated logo for twitter.

### ISSUE THREAD

**Issue by bhumika-1127** [Priyaaa1/StartConnect-Hub#126]
I would like to change the logo of twitter to updated one and add the link to it. @Priyaaa1 assign this task to me under GSSOC'24. 
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/137604220/4151b54c-3bae-45c2-a68d-047259a8d10a)

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Harsha19-08** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by bhumika-1127** [comment]
@Priyaaa1 Let me know if you need help with this issue by assigning it to me

**Comment by Priyaaa1** [comment]
@bhumika-1127 this has been done, raise any other issue.
