### ISSUE TITLE
Navbar is not responsive 598px to 1000px

### ISSUE THREAD

**Issue by Hariom01010** [Priyaaa1/StartConnect-Hub#128]
**Describe the bug**
The navbar becomes unresponsive from 600px to 730px and the logo is too big from 730px to 1000px

**To Reproduce**
1. Go to the Site
2. Open the Site in Inspect mode (Ctrl+Shift+I)
3. Resize the navbar to 600px - 1000px range

**Expected behavior**
The navbar text should not extend to next line until 730px and the navbar should convert to hamburger type from 600px to 730px
The navbar should look like this from 600px to 730px
![Screenshot 2024-05-15 115732](https://github.com/Priyaaa1/StartConnect-Hub/assets/109733360/4c2aef71-cb5c-493e-8c8d-891c63dc5c1e)

And should look like this from 730px to 1000px
![Screenshot 2024-05-15 115725](https://github.com/Priyaaa1/StartConnect-Hub/assets/109733360/935c5009-f567-4def-8a01-edcf524ad5b0)

**Screenshots**
![Screenshot 2024-05-15 115415](https://github.com/Priyaaa1/StartConnect-Hub/assets/109733360/766dca55-81c5-4b90-9738-8429507c3a32)

![Screenshot 2024-05-15 115441](https://github.com/Priyaaa1/StartConnect-Hub/assets/109733360/cfd99c63-fd29-4af6-8fc3-48663903c383)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Chrome Version 124.0

**Smartphone (please complete the following information):**
Doesn't apply. Responsiveness was checked using Chrome's Inspect tool on PC

Please assign the issue to me under GSSOC.

**Comment by TitikshyaChanda** [comment]
Kindly assign me this issue. I am proficient in front end development which includes html,css,javascript and framework like react.js
