### ISSUE TITLE
Replace phone number field with email field and submit contact form using web3 forms

### ISSUE THREAD

**Issue by OmKanhe** [Priyaaa1/StartConnect-Hub#13]
**Description:**

Currently, the contact form on the website includes a phone number field for users to enter their contact information. However, I propose replacing the phone number field with an email field to improve user experience and facilitate communication. Additionally, I suggest implementing the contact form submission using web3 forms (https://web3forms.com/) for enhanced reliability and functionality.

**Proposed Solution:**

I plan to update the contact form by replacing the phone number field with an email field. This modification will align the form fields with standard contact form conventions and enable users to provide their email addresses for communication purposes. Additionally, I will implement the form submission using web3 forms, leveraging their robust features and integration capabilities. The new form will include validation checks to ensure that the email field is filled out correctly before submission.

Additional Information:

- I have experience working with web development technologies, including MERN stack and web3 forms.
- I am committed to delivering a seamless user experience and improving the functionality of the contact form.
- If there are any specific design preferences or integration requirements for the updated contact form, please provide guidance, and I will accommodate them accordingly.

**Comment by divyanshahlawat** [comment]
I would like to work on this feature, can you assign this issue?

**Comment by Priyaaa1** [comment]
@OmKanhe do you want to work on this?
