### ISSUE TITLE
Enhance Footer 

### ISSUE THREAD

**Issue by Hemashree21** [Priyaaa1/StartConnect-Hub#134]
The footer in the website kind of looks bland and not that eye-catching. I want to redesign the footer with Copyright claims and different links. Here are some of the footers I had worked on previously.

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/138188163/91e8a2a4-d130-4e55-bd7c-4a8b31525263)

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/138188163/a3d4c51d-c78a-409c-9e37-e6d9fc13b2d8)

I can redesign it according to the color theme of the project. Please assign this issue to me.

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently Footer page has not such a good style .

*Describe the solution you'd like*
Adding margin, padding and set allginment and change in font and changes according to Footer

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me
