### ISSUE TITLE
Minor grammatical improvements and specificity in commit message instructions

### ISSUE THREAD

**Issue by thevijayshankersharma** [Priyaaa1/StartConnect-Hub#135]
Is your feature request related to a problem? Please describe.
The current version contains several minor grammatical errors such as "Perfom" instead of "Perform" and "suppose" instead of "supposed". Additionally, the instructions for committing changes could be clearer and more specific.

Describe the solution you'd like
I would like to correct these grammatical errors and provide a more specific example for the commit message instructions to improve clarity and usability.

**Comment by Sooraj002** [comment]
I would like to fix this issue.

**Comment by thevijayshankersharma** [comment]
@Priyaaa1 Could you add the gssoc label and the level label too ?
