### ISSUE TITLE
LOG IN and SIGN UP  should be in one button.

### ISSUE THREAD

**Issue by Varnika2526** [Priyaaa1/StartConnect-Hub#137]
**Is your feature request related to a problem? Please describe.**
An already logged-in user can be made to have direct access to the website, One who has not Signed up on the website can Sign up using the link that will open on clicking "SIGN UP" 

**Describe the solution you'd like**
Make a Button on the navbar that will contain the Login Form and at the bottom of the form, A link will be provided within "Sign up" redirecting it to the Sign-up form.

**Additional context**
@Priyaaa1 Kindly assign me this task under GSSOC'24.

**Comment by Isha1233** [comment]
@Priyaaa1 I want to work on this issue kindly assign this issue to me
