### ISSUE TITLE
Genuine Number is not checked while sending message

### ISSUE THREAD

**Issue by kesharwaniyanshi** [Priyaaa1/StartConnect-Hub#138]
**While sending message to the author/owner tne phone number field takes input any data (characters ,numbers,letters).**
This should be taken care of to avoid increasing spam storage data. The Phone Number field should correctly accept the numbers only . Please assign me this issue so that i can fix it.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/123561974/25a1c271-714a-43d9-b2f6-263aed239fc6)

**Comment by Isha1233** [comment]
@Priyaaa1 kindly assign this task to me
