### ISSUE TITLE
Display Successfully sent message after sending message

### ISSUE THREAD

**Issue by kesharwaniyanshi** [Priyaaa1/StartConnect-Hub#139]
After sending a message it should  display a Successfully sent note so that the user knows that the message was sent successfully without failure.Otherwise the page reloads and user has no idea whether message was sent or not.
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/123561974/841dc6c2-5e45-44d4-a47f-c6d4cf508891)
Please assign this issue to me. I have knowledge in HTML,CSS,JS,React and have don similar implications on my personal portfolio.

**Comment by 8deepakkumar8** [comment]
pls label this and assign the task to me , i would like to work on it

**Comment by kesharwaniyanshi** [comment]
Please assign this issue to me.
