### ISSUE TITLE
 Implement Dark and Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [Priyaaa1/StartConnect-Hub#140]
**Is your feature request related to a problem? Please describe.**
Users desire the ability to toggle between dark and light modes within the application for enhanced readability and reduced eye strain. Currently, this feature is lacking, resulting in a less customizable and potentially discomforting user experience.

**Describe the solution you'd like**
Integrate a simple toggle switch within the application interface, allowing users to effortlessly switch between dark and light modes. Dark mode should feature darker color schemes for improved readability, particularly in low-light environments.

**Additional context**
The integration of a dark/light mode toggle aligns with modern user preferences and usability standards. Providing this feature enhances user satisfaction and improves overall usability. Additionally, it can be implemented seamlessly within the existing application interface, adding value to the user experience without significant disruption.

**Comment by 8deepakkumar8** [comment]
pls assign the label,
i would like to work on it, pls assign this task to me

**Comment by Isha1233** [comment]
@thevijayshankersharma I will Implement it using react, tailwind CSS where there is a toggle button for changing mode by making a separate file where I will write code and then using tailwind implement it in whole project. Kindly assign this task to me

**Comment by Priyaaa1** [comment]
@thevijayshankersharma @8deepakkumar8 @Isha1233  this issue has been resolved
