### ISSUE TITLE
Broken Footer Links & Validation Additions for Login and SignUp Forms

### ISSUE THREAD

**Issue by kushalkumar1362** [Priyaaa1/StartConnect-Hub#142]
### 1.  Footer section links are broken : 

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/140513098/957fe11f-456e-4025-9870-b16624524980)

### 2. Add Validation for login Form:

![Screenshot (345)](https://github.com/Priyaaa1/StartConnect-Hub/assets/140513098/083153c7-465a-4090-8a0d-15320737d896)

### 3. Add Validation for SignUp button:

![Screenshot (346)](https://github.com/Priyaaa1/StartConnect-Hub/assets/140513098/24680b0d-aaba-4f0c-85f3-a98791a53847)

**Comment by Priyaaa1** [comment]
@kushalkumar1362 this has been done
