### ISSUE TITLE
The UI of the footer is not responsive

### ISSUE THREAD

**Issue by Chelsea67jain** [Priyaaa1/StartConnect-Hub#145]
A observed that the UI of the footer is not responsive for mobile devices. I can make it responsive using grid and media queries.

Screenshots:
![Screenshot_20240516_231853](https://github.com/Priyaaa1/StartConnect-Hub/assets/100270122/c15cddd9-f13e-4729-a08e-55212a688625)

I can make the footer more interactive just like this: 
![IMG_20240516_233632](https://github.com/Priyaaa1/StartConnect-Hub/assets/100270122/4cd9e3ed-aacf-4e90-a385-80638a70da98)

@Priyaaa1 Can you allocate me this issue under GSSoC2024?

**Comment by Harsha19-08** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by Tejsvapandey1** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24
