### ISSUE TITLE
Add Attractive Hover Effect to Testimonials Card Section

### ISSUE THREAD

**Issue by HK853** [Priyaaa1/StartConnect-Hub#146]
Description: Request to enhance the UI by adding an attractive hover effect to the testimonials card section to improve user engagement and visual appeal.

Proposal: Implement a smooth transition effect on Testimonial section

**Comment by HK853** [comment]
https://github.com/Priyaaa1/StartConnect-Hub/assets/113816862/1dc38803-5c1c-4fa3-b80a-c93ed1244d92

after adding hover its looks like this.

**Comment by Hemxnt** [comment]
assign me this issue

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .
