### ISSUE TITLE
[Footer] : The pages they are referring are empty 

### ISSUE THREAD

**Issue by Priyanshu2743** [Priyaaa1/StartConnect-Hub#152]
Hii @Priyaaa1 

As a new user, I will go to footer for searching about the website, owner and its idea links 

I can design different components for the components and then linking them with it 
Using Hovering effect and interactive UI for the Components and the new components which it refer will contribute towards user interaction. 
I am a gssoc2024 contributor. could you assign me this task under gssoc and add the level to this

<img width="960" alt="Screenshot 2024-05-17 182832" src="https://github.com/Priyaaa1/StartConnect-Hub/assets/124867297/ea85f67a-c74e-4bbd-84b7-022ecb3e856d">
<br> 
I can create the UI for it under gssoc2024

**Comment by Sooraj002** [comment]
I would like to fix this issue.

**Comment by Priyanshu2743** [comment]
Hii @Priyaaa1 

I can design different components for the components and then linking them with it
Using Hovering effect and interactive UI for the Components and the new components which it refer will contribute towards user interaction

 could you assign this task to me under gssoc
