### ISSUE TITLE
Adding animations to the home page 

### ISSUE THREAD

**Issue by reshamsai150** [Priyaaa1/StartConnect-Hub#153]
Animations grab users’ attention and encourage them to explore further.
They add dynamic effects to a website home page 

I would like to contribute to this issue @Priyaaa1 

https://github.com/Priyaaa1/StartConnect-Hub/assets/164533685/32528e71-1ea3-4057-b3a7-c4cc3a58d920

**Comment by Priyaaa1** [comment]
@reshamsai150 Thankyou but this animation is not needed now
