### ISSUE TITLE
Add vision and mission page

### ISSUE THREAD

**Issue by Devaki01** [Priyaaa1/StartConnect-Hub#154]
### Description of problem
When clicked on the the vision and mission feature present in the footer section, page not found error appears. 

### Proposed Functionality
I would like to contribute by adding a responsive, engaging and user-friendly webpage with meaningful content for vision and mission feature. 

### Why add Vision and Mission feature
Vision and Mission is essential component of brand-identity and provides direction and purpose to the employees. Also, it wins customer trust and loyalty and thus enhance credibility.

### About me 
I am a tech-enthusiast and an aspiring developer, passionate about Front-end technologies such as React. As a GGSoC'24 contributor, I am eager to work on this functionality and promise to put all my efforts to deliver the best results.

Please assign me this issue under GGSoC'24. 

<img width="194" alt="image" src="https://github.com/Priyaaa1/StartConnect-Hub/assets/147143243/e11025b2-0adb-41fe-b43a-950526fcc9a7">

**Comment by Devaki01** [comment]
@Priyaaa1 Thank you for the opportunity. Will start working on it immediately.

**Comment by drick-infinity** [comment]
can you assign this issue to me under gssoc'24 and let me know what content should you need under vission and pages If you have an content let me know I give proper designing the page with better css or tailwind css I eager to add this feature as i am mern developer i used develop react pages frequently.

**Comment by n14rishitha** [comment]
Hi @Priyaaa1 

I would like to work on this issue . so please assign this task to me
