### ISSUE TITLE
Bug: "Link FAQ Section" to the Footer Section

### ISSUE THREAD

**Issue by MastanSayyad** [Priyaaa1/StartConnect-Hub#157]
Hey @Priyaaa1,

**Minor changes:** Currently the link is empty for FAQ section in footer, I would like to navigate the link for FAQ section In footer

https://github.com/Priyaaa1/StartConnect-Hub/assets/101971980/f39ad820-6444-45ed-8586-a58123234cff

Could you please **assign this issue to me under GSSOC 24**?

**Comment by Harsha19-08** [comment]
I would like to work on this issue. Can you assign it to me?
