### ISSUE TITLE
About us link is not working in footer section

### ISSUE THREAD

**Issue by harikasayani** [Priyaaa1/StartConnect-Hub#184]
**Describe the bug**
About us link in footer section is not working properly.

**Expected behavior**
I will make it to work.
I want to work on this issue.
Please assign me this issue.

**Comment by Yuvraj960** [comment]
@Priyaaa1 Please assign this issue to me under GSSoC24

**Comment by n14rishitha** [comment]
Hi @Priyaaa1 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by DhanaAswini** [comment]
Please this task to me. I can clear the bug

**Comment by Hemxnt** [comment]
assign me this issue
