### ISSUE TITLE
Go to top and chatbot buttons overlapping

### ISSUE THREAD

**Issue by Priyaaa1** [Priyaaa1/StartConnect-Hub#189]
**Describe the bug**
The Go to top button and the chatbot button, there are overlapping and we can't see the chatbot is there due to Go to top button.

**Expected behavior**
The Go to top button should be in left bottom instead of right bottom.

**Comment by MastanSayyad** [comment]
Hey, @Priyaaa1 let me handle this issue as I was the one who implemented the Go to Top button, Please assign this issue to me under GSSOC'24.

and yeah, here is the feature solution:

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/101971980/e5090957-07dc-4087-883b-faa910dd2da2)
