### ISSUE TITLE
navbar dropdown animation

### ISSUE THREAD

**Issue by Sypher0Dronzer** [Priyaaa1/StartConnect-Hub#191]
**Is your feature request related to a problem? Please describe.**
There is no animation for navbar dropdown for mobile responsive devices 

**Describe the solution you'd like**
I would like to create an animation for the drop down 

**Additional context**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/83546205/adfa384b-589e-41fa-92d9-ebf2e77992fa)

please assign this issue to me @Priyaaa1

**Comment by DhanaAswini** [comment]
I can make the animations for navbar by adding dropdown menu. please assign the task to me
