### ISSUE TITLE
Footer and about us section not responsive

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Priyaaa1/StartConnect-Hub#202]
**Describe the bug**
When I visit the website from my phone, i could able to find that the footer and the about us sections are not responsive. It collapse the responsiveness of enture landing page

**To Reproduce**
1. Go to the landing page of the website and scroll down to see the responsiveness

**Expected behavior**
Make footer and about us section responsive

**Screenshots**
![Screenshot_20240520_143822_Chrome](https://github.com/Priyaaa1/StartConnect-Hub/assets/139672976/6292e9bf-81e6-4ffe-a9d4-e9472e28640a)
![Screenshot_20240520_142644_Chrome](https://github.com/Priyaaa1/StartConnect-Hub/assets/139672976/b6f949bc-f61a-4ac0-8084-2ba28bca856f)

**Smartphone (please complete the following information):**
 - Device: A04
 - OS: android 
 - Browser: chrome

**Comment by Albert-2** [comment]
hey @Priyaaa1 
I would love to contribute to this issue
can you please assign me the same
Thank You...!!:)
