### ISSUE TITLE
Add show password feature in login form

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Priyaaa1/StartConnect-Hub#204]
**Is your feature request related to a problem? Please describe.**
In current login form there is no option to see the password.

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/139672976/ac232b42-e236-4bb3-b42e-2c29164a9a89)

**Describe the solution you'd like**
I would like to add that option which looks like below
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/139672976/b9c38498-59a2-460f-997e-4d42b520ae37)

Please assign this issue to me to add this feature.

**Comment by tanishkagupta27** [comment]
Hi @Priyaaa1,
Hope this message finds you well. 
I have relevant knowledge to solve this issue. 
Please assign me this issue under @GSSOC'24.

**Comment by DhanaAswini** [comment]
Please assign the task to me. I can make the password visibile using certain button or icons.

**Comment by rajshivam0432** [comment]
hello mam @Priyaaa1 please assign me this
