### ISSUE TITLE
FIX: LOGIN REGISTER AND LOGIN UI 

### ISSUE THREAD

**Issue by dinxsh** [Priyaaa1/StartConnect-Hub#21]
will improve the ui with pure tailwind css and make it responsive and more visually appealing 

also the navbar and footer is invisible and not aligned properly as shown below will fix that as well

currently 
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/90450035/95b9fee3-860a-4688-a122-d194084a059e)

**Comment by dinxsh** [comment]
hi @Priyaaa1, could you kindly assign me this under gssoc?

**Comment by sahi123-cloud** [comment]
can u please add the label gssoc and assign the task for me

**Comment by spywolf2049** [comment]
My expertise and skills in web development could greatly contribute to the success of this endeavor. I believe that my insights and contributions would play a crucial role in creating a user-friendly and efficient authentication process for our users.

Here are some key features and functionalities i will add in the Login and Registration Page:

Secure user authentication with password hashing and encryption.
User-friendly interface with clear instructions and error handling.
Seamless integration with our existing database and backend services.
Customizable user profiles with options for personalization.
Implementation of best practices for data protection and privacy compliance.

**Comment by Manujdixit** [comment]
Hey @Priyaaa1 could you assign me this issue, I can fix-
the login and sigup page, routing, navbar .

**Comment by Anou25** [comment]
Hi @Priyaaa1 ,I want to work on this issue please assign it to me, I will make it more appealing and better as I even have experience in frontend as well as ui designing.

**Comment by dinxsh** [comment]
hi @Priyaaa1, could you please assign the issue to me

**Comment by Kiran-116** [comment]
Can you please assign this issue to me under GSSoC'24. I will improvise the UI and make it responsive and more visually appealing, and fix the issue of Navbar and Footer.

**Comment by Abhishek0732** [comment]
@Priyaaa1 can you please assign it to me I will make the sign up and login page more ui friendly and the navbar which  is not visible will also be fixed.

**Comment by Rv43** [comment]
Can you please assign this issue to me I want to work on this issue pls

**Comment by Yuvraj960** [comment]
@Priyaaa1 Please assign this issue to me under GSSoC24, you can see my contributions, I will make it look very much appealing

**Comment by n14rishitha** [comment]
Hi @Priyaaa1 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by Srihithakillana** [comment]
Hello @Priyaaa1,
I can work on this issue and can improve the UI, please assign this task to me.
