### ISSUE TITLE
Add Dark mode and light mode toggle

### ISSUE THREAD

**Issue by Hemashree21** [Priyaaa1/StartConnect-Hub#213]
I want to work on making the website in dark mode so that users can toggle between the mode of their choice.
@priyaa1 can you please assign this issue to me?

**Comment by Harshsaini001** [comment]
Hey @Priyaaa1 , I want to work on this issue. Plz assign this to me.

**Comment by Hemashree21** [comment]
@Priyaaa1 should I work on this since you have added the labels? Can you please assign this?

**Comment by rajshivam0432** [comment]
@Priyaaa1 i want to work on this issue. please assign  me

**Comment by Hemxnt** [comment]
assign me this issue

**Comment by Priyaaa1** [comment]
@Hemashree21 Kindly make changes within 2 days, otherwise this task will be given to someone else

**Comment by n14rishitha** [comment]
Hi @Priyaaa1 

II would like to work on this issue . so please assign this task to me .I can complete it .
