### ISSUE TITLE
💡[Bug]: Chatbot goes behind the testimonial section

### ISSUE THREAD

**Issue by Priyanshu2743** [Priyaaa1/StartConnect-Hub#215]
**Describe the bug**
The Chatbot goes behind the testimonials section due to which it becomes odd for a user to see such things in a website 

**To Reproduce**
1. Go to 'Testimonial Section'
2. Click on 'Chatbot icon'
3. See Bug

**Expected behavior**
The Chatbot shows above the testimonials section due to which it becomes odd for a user to see such things in a website 

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/124867297/f4a9b628-4571-4f44-b148-0266c59c75e6)

I can remove this bug and 
### can improve the overall UI of the website

Pls assign this task under GSSOC to me and add labels of it

**Comment by Priyaaa1** [comment]
@Priyanshu2743 this issue has been resolved
