### ISSUE TITLE
[Feature]: Vision and Mission in footer is not working

### ISSUE THREAD

**Issue by Priyanshu2743** [Priyaaa1/StartConnect-Hub#217]
**Is your feature request related to a problem? Please describe.**
Vision and Mission in footer is not working

### Describe the solution you'd like
I will create a Userfriendly UI for this page 

### Additional context
I will make it to work.
I want to work on this issue.
Please assign me this issue. under gssoc and level label

**Comment by DhanaAswini** [comment]
Please assign this to me. I can make it work

**Comment by Priyaaa1** [comment]
@Priyanshu2743 it's working now
