### ISSUE TITLE
Enhance Navigation Bar with Hover Effects

### ISSUE THREAD

**Issue by avanimathur** [Priyaaa1/StartConnect-Hub#23]
Description:
Adding a hover effect to the elements of a navigation bar enhances user experience by providing visual feedback. 
This will increase interactivity and improve the overall usability.

![Screenshot (210)](https://github.com/Priyaaa1/StartConnect-Hub/assets/151984867/b14d70cf-7939-483e-bc74-5af604c32ee8)

This contribution is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign this issue to me.

**Comment by sahi123-cloud** [comment]
can assign this issue to me and please add the label gssoc

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributer i would like to work on this project. I request you to assign this project for me @Priyaaa1

**Comment by SalehaTabassum** [comment]
@Priyaaa1 please assign this issue to me.i will add the hover effect and solve it

**Comment by AshutoshVerma140404** [comment]
please assign  me this issue

**Comment by psychic-coder** [comment]
Hello I am Rohit Ganguly ,I am a Frontend Developer,  I would like to contribute to this project , can you please assign me this project.

**Comment by gayathrik23** [comment]
@Priyaaa1  can you assign this issue to me under Gssoc'24

**Comment by vinay02103** [comment]
hello Mentor,I'd want to contribute to this project as a GSsoc'24 contributor. Please give me this issue to work on.

**Comment by rishuraj1708** [comment]
hey there, i would like to work on this issue. I request you to assign this project for me .
