### ISSUE TITLE
Add icons beside home, about, testimonials, FAQ's , contact and login

### ISSUE THREAD

**Issue by Saimanjari777** [Priyaaa1/StartConnect-Hub#230]
**Is your feature request related to a problem? Please describe.**
The icons beside the home, about, testimonials, FAQ's, contact, and login are missing.

**Describe the solution you'd like**
I would like to add the icons to enhance the website.

**Additional context**
I am working under GSSoC'24
Please assign this issue to me @Priyaaa1

**Comment by Priyaaa1** [comment]
@Saimanjari777 this is not needed now
