### ISSUE TITLE
Navbar UI distorted

### ISSUE THREAD

**Issue by govindumeesala** [Priyaaa1/StartConnect-Hub#231]
**Is your feature request related to a problem? Please describe.**
Navbar is not expanded wholly till the very end of right hand side

**Describe the solution you'd like**
Enhancing Navbar UI by expanding wholly.

**Additional context**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/129055361/3e9e2099-449c-46c0-b218-4995de2e6906)

**Comment by DhanaAswini** [comment]
Please assign this to me. I can make the navbar look really appealing and user friendly\

**Comment by Monalisha-Roy** [comment]
please assign this issue to me under GSSOC 2024.  I can finish this task quickly and perfectly.
