### ISSUE TITLE
Disalignment of cards and arrow buttons in Testimonials section 

### ISSUE THREAD

**Issue by govindumeesala** [Priyaaa1/StartConnect-Hub#232]
**Is your feature request related to a problem? Please describe.**
Testimonials UI is slightly disaligned. cards are overlapping with arrow buttons.

**Describe the solution you'd like**
Aligning the cards and arrows correctly in testimonials will improve its UI and better user experience.

**Additional context**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/129055361/b22e57ed-6eee-419d-a98f-f19edb9434b0)

**Comment by Bhanuteja01** [comment]
@Priyaaa1 i like too work on this issue!! 
can you assign me this issue
