### ISSUE TITLE
Adding Investor Management Page in Explore More

### ISSUE THREAD

**Issue by Varnika2526** [Priyaaa1/StartConnect-Hub#239]
**Is your feature request related to a problem? Please describe.**
Adding Investor Management Page in Explore More Page 

**Describe the solution you'd like**

**Additional context**
@Priyaaa1 kindly assign me this issue under GSSOC'24

**Comment by K-21** [comment]
can you please assign me this issue under gssoc24

**Comment by shreyasupe35** [comment]
Hi @Priyaaa1 ,I would like to improve the ui of the Investor mangement Page as it looks boring ,please assign me this issuse I will try my best to provide a better ui for the investor management page.Please assign me the issue
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/115993492/66d049e9-51ef-4b0b-8cab-e76c06827caf)

**Comment by Priyaaa1** [comment]
@shreyasupe35 you can create your issue regarding enhancement of the page you want to improve. This issue of adding the investor management page has been completed, so this issue will be closed.
