### ISSUE TITLE
Bug: The menu icon in mobile view doesnt lead to a vertcal sidebar/navigation bar

### ISSUE THREAD

**Issue by PSP2706** [Priyaaa1/StartConnect-Hub#24]
This bug report addresses an issue where the menu icon in the mobile view fails to activate the vertical sidebar or navigation bar as intended. Users are unable to access navigation options on mobile devices due to this malfunction. The description will involve identifying the root cause of the problem and implementing the necessary fixes to ensure that the menu icon correctly triggers the vertical sidebar/navigation bar on mobile devices.

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributer i would like to work on this project. I request you to assign this project for me @Priyaaa1

**Comment by FrostyFeet-coder** [comment]
As a GSsoc'24 contributer i would like to work on this project. I request you to assign this project for me @Priyaaa1
