### ISSUE TITLE
Feature for auto commenting on a new issue creation

### ISSUE THREAD

**Issue by suhanipaliwal** [Priyaaa1/StartConnect-Hub#242]
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by MohanRamSridhar** [comment]
can you assign this issue to me I would also like to add a feature that will self assign the issue to a user if he or she wants to contribute to the issue given he or she has opened the issue
