### ISSUE TITLE
Page Directory is incorrect

### ISSUE THREAD

**Issue by Aanyaa26** [Priyaaa1/StartConnect-Hub#247]
**Describe the bug**
From Explore more page when clicking back on testimonials or any other button on navbar except home ...it is redirecting it to home page only and not the respective page when clicked!
It must be corrected

**To Reproduce**
1. Go to 'home page'
2. Click on 'explore more'
3. click on testimonials
4. The error is is that it will bring back to home page and not the testimonial section directly

**Expected behavior**
Instead upon clicking testimonials or about or any other item in the navbar except home page must redirect to that particulate section of home page only and not the home page!

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/128315909/b8044967-fce1-47b4-bf4e-d09def03c7c6)
![Screenshot 2024-05-23 213529](https://github.com/Priyaaa1/StartConnect-Hub/assets/128315909/1c378725-5bf6-4a82-992b-de17cc0111c3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version i5

**Comment by naisargi17** [comment]
can you please assign me under GSSOC.'24 .
