### ISSUE TITLE
Add Legal Pages - Terms & Conditions, Cookie Policy and Privacy Policy

### ISSUE THREAD

**Issue by Hemashree21** [Priyaaa1/StartConnect-Hub#251]
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/138188163/432030b2-f61b-48bc-b47e-00d1a5af9b9e)

The Links of the Legal pages are not working in the footer and I want to work on designing them. I will make sure that the pages are responsive as well. 

@Priyaaa1 can you please assign this issue to me?

**Comment by Priyaaa1** [comment]
@Hemashree21 this issue has been resolved
