### ISSUE TITLE
Add a dynamic year code

### ISSUE THREAD

**Issue by arpit4521** [Priyaaa1/StartConnect-Hub#256]
![Screenshot 2024-05-24 135601](https://github.com/Priyaaa1/StartConnect-Hub/assets/127679958/6f412e26-6fe8-4ba4-8697-7d5d26020ce2)

> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> BUG: Add dyanamic year code so that one doesnot need to change it every year using javascript function. !
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

**Comment by arpit4521** [comment]
@Priyaaa1 please assign me this under gssoc so that i can fix it asap

**Comment by vipinrao009** [comment]
please assign this feature to me.Hope I would complete it within few minutes
