### ISSUE TITLE
Footer navigations are not linked.

### ISSUE THREAD

**Issue by Annu117** [Priyaaa1/StartConnect-Hub#257]
**Describe the bug**
OnClick pages are not loaded.
**To Reproduce**
Go to the footer section.
Click to re-direct links like "About Us".

**Expected behaviour**
Re-direct to the particular section.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/108427028/6516e3f4-49ac-485a-80fc-a7f88258f3ef)
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/108427028/1a06369a-b0e6-410f-b80a-f52062d9a4b6)

**Additional context**
The footer is not designed properly. I would like to improve the footer section. @Priyaaa1 can u plz assign this to me under gssoc'24.

**Comment by DhanaAswini** [comment]
Please assign this to me

**Comment by Priyaaa1** [comment]
@Annu117 the footer section has changed, still navigations aren't linked. You can work on that.

**Comment by Priyaaa1** [comment]
@DhanaAswini task will be assigned on the basis of First Come First Serve. If the assignee doesn't complete it within 2-4 days, I'll assign you the task.

**Comment by Shobhitsingh-2503** [comment]
I can see this issue is not fixed yet, can this issue be assigned to me ? @Annu117
