### ISSUE TITLE
Improving Login and Sign up page

### ISSUE THREAD

**Issue by akankshachanana1** [Priyaaa1/StartConnect-Hub#26]
**Is your feature request related to a problem? Please describe.**
The sign-up and log-in websites are currently not very user-friendly.
To improve it, I want to make some adjustments.

**Additional context**

https://github.com/Priyaaa1/StartConnect-Hub/assets/127978268/b7172c6a-78e8-4082-9b2d-29ef60beb4ab

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributer i would like to work on this project. I request you to assign this project for me

**Comment by Manujdixit** [comment]
I can fix the login and signup page, currently it is not having full height and navbar is also not visible. Can you please assign me this issue.

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me, I will make it more appealing and better.

**Comment by Deepthi-Ramineni** [comment]
I would like to work on it. Can you please assign this to me under GSSoC 2024....???
