### ISSUE TITLE
Page Does Not Scroll to Top on Route Change

### ISSUE THREAD

**Issue by pani2004** [Priyaaa1/StartConnect-Hub#260]
When navigating to a new route, such as /howitworks, the page content opens at the bottom, requiring the user to click the scroll to top button to go to the top to see the beginning of the page content. This behavior is not user-friendly and impacts the user experience, as users expect to start at the top of the new page content when navigating through routes.

https://github.com/Priyaaa1/StartConnect-Hub/assets/154724111/012c5825-0cbf-488f-b230-dbb6e79bc9c1

**Comment by pani2004** [comment]
@Priyaaa1 can u assign me this I can fix this!!!!. GSSOC'24 Contributor.

**Comment by Priyaaa1** [comment]
@pani2004 the footer has been changed now, kindly raise some other issue.
