### ISSUE TITLE
Login form UI can be enhanced. 

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [Priyaaa1/StartConnect-Hub#268]
**Is your feature request related to a problem? Please describe.**

[Screenshot 2024-05-25 112449](https://github.com/Priyaaa1/StartConnect-Hub/assets/124513264/893f6728-af39-4821-bec7-9a17c4bfda62)

There is very less space between the different component of login form. So its padding and margin can be managed and it can be align at the center of the page.
**Describe the solution you'd like**
Managing the padding and margin ratio in the form.
**Additional context**

**Comment by AnirbanChattopadhyay-2004** [comment]
Please assign this issue to me so that I can have a contribution under gssoc24. Please add labels and gssoc tag for this issue.

**Comment by Priyaaa1** [comment]
@AnirbanChattopadhyay-2004 this issue has been resolved.
