### ISSUE TITLE
Implementing Multilingual support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [Priyaaa1/StartConnect-Hub#270]
I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.
The below image is my last project where I made it available in different languages.
**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/139578011/91c8b17d-84ec-4ca4-87d1-d01ed47a5abb)
**

**Comment by Priyaaa1** [comment]
@Anjankumarkamalapur do you want to work on this?
