### ISSUE TITLE
ChatBot logo going below Navbar

### ISSUE THREAD

**Issue by govindumeesala** [Priyaaa1/StartConnect-Hub#272]
**Describe the bug**
When chatbot is opened, its logo is going below the navbar.

**To Reproduce**
1. Go to chatbot
2. Click on 'click on logo
3. logo will be seen going under navbar

**Expected behavior**
logo of chatbot should be above any other element in the website. And providing pointer when hovered on logo enhances user experience.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/129055361/ede1bdef-4d32-4fbc-8e40-e18f6e62a6c3)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome

**Comment by DhanaAswini** [comment]
please assign this to me
