### ISSUE TITLE
Feat/ChatBot ui is not good

### ISSUE THREAD

**Issue by drick-infinity** [Priyaaa1/StartConnect-Hub#279]
**Is your feature request related to a problem? Please describe.**
Chat Bot ui is not good its tags are not properly alignes as chatbot have

**Describe the solution you'd like**
Using better margin and padding or colours according to theme is suggested as blue etc. bvarious colours according matches to theme

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the StartConnect-Hub project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by Priyaaa1** [comment]
@ShahHetviIT thankyou, but the task will be assigned on the basis of First Come First Serve. If the assignee will not complete the task within 2-3 days, it will be assigned to you.

**Comment by ShahHetviIT** [comment]
okay!
