### ISSUE TITLE
Adding Icons

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Priyaaa1/StartConnect-Hub#280]
Adding icons for different sections on the navbar such as home , about , contact etc would make it look for effiecient and enhance user experience.

**Comment by Soumya6Tiwari** [comment]
@Priyaaa1 kindly assign me this issue under gssoc'24

**Comment by Soumya6Tiwari** [comment]
@Priyaaa1  being a project admin , atleast let us know the status of our issue , and kindly assign me this issue , looking forward to it.

**Comment by Tanishka023** [comment]
Hey @Priyaaa1 I can fix this issue easily please assign this to me

**Comment by Priyaaa1** [comment]
@Soumya6Tiwari there are already issues raised for this, but I think icons would look good in footer, not in navbar.. so I also told to a contributor about that. You must search in the issues about your issue first, then you should raise your issue if it's not there.
