### ISSUE TITLE
Adding a dark mode 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Priyaaa1/StartConnect-Hub#281]
Adding  a dark mode option on the navbar which will change the overall them of the webpage to dark mode .

**Comment by Soumya6Tiwari** [comment]
@Priyaaa1  kindly assign me this issue under gssoc'24

**Comment by Priyaaa1** [comment]
@Soumya6Tiwari there is already a issue for adding dark mode feature. Kindly do not spam by raising same issue again and again.
