### ISSUE TITLE
[Bug]:- UI for the Explore More Page is Distorted

### ISSUE THREAD

**Issue by Priyanshu2743** [Priyaaa1/StartConnect-Hub#287]
**Describe the bug**
The UI for the explore more page is distorted for smaller screens which creates a very bad impact on users as a lot of users prefer to work on small screen laptops today

**To Reproduce**
1. Go to 'Website'
2. Click on 'explore more'
3. See error

**Expected behavior**
The UI should be neat and clean and Interactive

**Screenshots**

https://github.com/Priyaaa1/StartConnect-Hub/assets/124867297/6bdcfa26-888e-4393-8b47-f0460cfb5b99

### I can Improve it under Gssoc 
Kindly assign me this issue under gssoc and add labels of level 3

**Comment by Priyaaa1** [comment]
@Priyanshu2743 this task is not of level3, I'm assigning this with level2.
Will change it if needed.
