### ISSUE TITLE
Lack of proper spacing in footer elements (among themselves) and also between login form and footer

### ISSUE THREAD

**Issue by rajRishi22** [Priyaaa1/StartConnect-Hub#3]
![Screenshot 2024-05-09 004725](https://github.com/Priyaaa1/StartConnect-Hub/assets/98014028/48676223-04c6-42c9-af8f-66f8ba3e4080)
Issues that need to be fixed :
1. There should be some amount of padding between footer elements .
2. On opening login or sign up form , footer moves to middle of the page , ideally it should stay at the bottom.

**Comment by rajRishi22** [comment]
I can work on these issues as I have worked on similar tech stacks and currently doing an intern also on same domain.

**Comment by CharanAdithya6505** [comment]
i have good experience in fronted part , i did great projects on fronted , could you please assign it will do it

**Comment by dhruv389** [comment]
Could you please assign me this issue ?  i am full stack Developer at beginner level , i want to try to solve this issue.

**Comment by Shyambarua** [comment]
Assign this issue to me.
As a full Stack Developer and 1 Year experience I can Write optimized code and Make it responsive.

**Comment by ShoveetSingh** [comment]
Shoveet here,I can effortlessly provide proper spacing in the footer component of the website. 
I hope it would also be assign to me.
