### ISSUE TITLE
Making the contact page responsive 

### ISSUE THREAD

**Issue by pradeepSDE** [Priyaaa1/StartConnect-Hub#30]
On small screens the contact page gets affected very badly affecting the user experience.

I can precisely craft it for small and medium screen sizes. 

<img width="311" alt="Screenshot 2024-05-11 001223" src="https://github.com/Priyaaa1/StartConnect-Hub/assets/103747065/55cf082a-10b1-465c-90c4-f0673aba5581">
Please assign this issue to me so i can work on it and correct it

**Comment by harshita1611** [comment]
Hi, I would like to work on this issue, can you please assign it to me

**Comment by vinay02103** [comment]
hello Mentor,I'd want to contribute to this project as a GSsoc'24 contributor. Please give me this assignment to work on.
