### ISSUE TITLE
Fix typography in ui

### ISSUE THREAD

**Issue by Manujdixit** [Priyaaa1/StartConnect-Hub#31]
Hey @Priyaaa1 I can fix typography in the project.

Current typography-
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/94791934/59b30f91-c12d-433c-8c0e-3a0a756d639e)

Using some css the ui can be improved a lot..

can you please assign me this issue.

**Comment by avanimathur** [comment]
Please assign it to me.
