### ISSUE TITLE
Hamburg Menu

### ISSUE THREAD

**Issue by FrostyFeet-coder** [Priyaaa1/StartConnect-Hub#32]
**Describe the bug**
Hamburger menu not working on mobile devices 

**To Reproduce**
1. Go to 'site'in mobile device
3. Click on 'hamburger menu '

**Expected behavior**
It should show a menu of options to land on different sections 

**Additional context**
I can add gsap animation to make the hamburger menu more beautiful and functional

**Comment by Stacvirus** [comment]
It would be a pleasure to contribute on it
