### ISSUE TITLE
Add Hover on Submit

### ISSUE THREAD

**Issue by namandude** [Priyaaa1/StartConnect-Hub#326]
Hey !! 
I would like to add one feature in this already beautiful looking website, i wanted to add the hovering effect on the submit button in the contact section . 
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/118013565/bae17c20-c8da-4b75-9cb1-ce779f3a43ce)

**Comment by Shubhamsingh2110** [comment]
assign me this work @Priyaaa1 #326
