### ISSUE TITLE
Hovering effect in the footer section

### ISSUE THREAD

**Issue by namandude** [Priyaaa1/StartConnect-Hub#327]
Hey !! 
I wanted to add some little hovering effect in the footer section tags , links so that i looks more amazing and attractive while surfing.
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/118013565/6fdb3196-2f73-45ea-a1cb-7d9cba6077f7)

**Comment by drick-infinity** [comment]
can you assign this issue to me under gssoc'24
