### ISSUE TITLE
feature : Adding Privacy Policy page 

### ISSUE THREAD

**Issue by SadafKausar2025** [Priyaaa1/StartConnect-Hub#328]
**Is your feature request related to a problem? Please describe.**
there is link in the footer of privacy policy , I want to add a good page of privacy Policy in it

**Comment by SadafKausar2025** [comment]
Hey @Priyaaa1 
can you please assign me this issue

**Comment by Priyaaa1** [comment]
@SadafKausar2025 there is already a privacy policy page, just not linked in the footer

**Comment by SadafKausar2025** [comment]
ok
