### ISSUE TITLE
Contact Us section is not responsive

### ISSUE THREAD

**Issue by R1MO9** [Priyaaa1/StartConnect-Hub#33]
**Describe the bug**
"Contact Us" section is not responsive for mobile devices

**Comment by R1MO9** [comment]
Hello Mentor, under the GSSOC'24 i can contribute to this and can resolve the issue. 
please assign me to this issue and add labels

**Comment by aditya7483thakur** [comment]
Hello Mentor , Can you assign this issue to me !

**Comment by R1MO9** [comment]
@Priyaaa1 assign me to this issue and add label
