### ISSUE TITLE
Password toggle in the login page

### ISSUE THREAD

**Issue by Saimanjari777** [Priyaaa1/StartConnect-Hub#330]
**Describe the bug**
Hey, @Priyaaa1 I would like to add the eye symbol to the password in the login form which will toggle the password.

**To Reproduce**
1. Go to login page
2. Click on Password

**Expected behavior**
When we click on eye symbol it toggles

**Screenshots**
![Screenshot 2024-05-24 124235](https://github.com/Priyaaa1/StartConnect-Hub/assets/130165687/0b3df3ad-a2e8-4de8-8093-f1915a4f4c8d)
This is my previous work

**Additional context**
I am working under GSSoC'24
Please assign this issue to me

**Comment by Priyaaa1** [comment]
@Saimanjari777 this has been implemented.
