### ISSUE TITLE
Better hover effect on header

### ISSUE THREAD

**Issue by heli0707** [Priyaaa1/StartConnect-Hub#332]
**Is your feature request related to a problem? Please describe.**
when we hover on header elements that display link underlined so remove that and add a better hover effect
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/95361125/91aa620b-181d-4dd0-80ab-544bde610b3b)

**Describe the solution you'd like**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/95361125/0d45fada-cd60-4039-9f02-c1d900f03359)
improve the hover effect of the header

**Additional context**

**Comment by Tanishka023** [comment]
Hey @Priyaaa1 I can fix this issue easily please assign this to me

**Comment by Shubhamsingh2110** [comment]
Assign me this task @Priyaaa1 #332

**Comment by Priyaaa1** [comment]
@Tanishka023 kindly complete the task within 2-3 days.
And make the navbar look descent, not too much effects.. just simple hover :)

**Comment by Tanishka023** [comment]
> @Tanishka023 kindly complete the task within 2-3 days.
> And make the navbar look descent, not too much effects.. just simple hover :)

Sure!
