### ISSUE TITLE
Nav bar hover animations and animated login page

### ISSUE THREAD

**Issue by Harsha19-08** [Priyaaa1/StartConnect-Hub#335]
**Is your feature request related to a problem? Please describe.**
As we or hovering on the nav bar content it is showing the underline option which should be improvised to animated hover and making a cool login page 

**Describe the solution you'd like**
The solution is clear adding animations for the nav bar links and content and adding cool login animation for the website
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/127961910/36d477bd-d294-470d-b5c5-e184dad862b4)
in the above way the feature is improvised 

**Additional context**
@Priyaaa1 can u assign me this issue under so that i can work on making an enhancemnts to the website

**Comment by Harsha19-08** [comment]
@Priyaaa1 Check the PR once

**Comment by Harsha19-08** [comment]
@Priyaaa1 check it out the PR

**Comment by Priyaaa1** [comment]
@Harsha19-08 are you working upon it?
