### ISSUE TITLE
Fixing the footer

### ISSUE THREAD

**Issue by YadlaMani** [Priyaaa1/StartConnect-Hub#338]
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/133841094/ac7d5ebf-79c0-4663-87d4-7f29245d4ae0)
@Priyaaa1 assign me this issue under gssoc'24

**Comment by Komalpreet-Kaur112** [comment]
Hey @Priyaaa1 
I would love to work on this issue and make enhancements in the footer section.Please assign it to me.

**Comment by Shubhamsingh2110** [comment]
assign me this task #338

**Comment by Priyaaa1** [comment]
@Shubhamsingh2110 this task has been done
