### ISSUE TITLE
Add Dark Mode/Light Mode to the website

### ISSUE THREAD

**Issue by ritankarsaha** [Priyaaa1/StartConnect-Hub#339]
**Is your feature request related to a problem? Please describe.**
I wish to add dark mode/light mode to the webpage

**Describe the solution you'd like**
I would like to create e toggle button to toggle between light and dark modes in the website. This enhances the UI component of the website giving the user a nice UI experience.

**Additional context**
The user gets a sense of personalisation

**Comment by ritankarsaha** [comment]
Please assign me this issue under gssoc'24. Please also add the labels level and gssoc

**Comment by Mansii8224** [comment]
please assign me this task I had worked for same feature in my web app , you can check  here. https://github.com/Mansii8224/Ecommerece_website

**Comment by Tanishka023** [comment]
Hey @Priyaaa1 I can fix this issue easily please assign this to me

**Comment by Priyaaa1** [comment]
@ritankarsaha this issue has been resolved
