### ISSUE TITLE
Fix Navigation Issues and Restore Navbar Functionality in Login and Signup Sections

### ISSUE THREAD

**Issue by Pratik2401** [Priyaaa1/StartConnect-Hub#34]
The navigation menu item for "Home" fails to function properly, preventing users from navigating to the home page. Additionally, the navbar in the login and signup sections is unresponsive, impeding user interaction. These issues hinder website usability and navigation. This task aims to rectify the dysfunctionality of the home button and restore full functionality to the navbar in the login and signup sections. Resolving these navigation issues will enhance user experience and improve website usability.

**Comment by vinay02103** [comment]
I'd want to contribute to this project as a GSsoc'24 contributor. Please give me this assignment to work on.
