### ISSUE TITLE
The Google Login/Sign In button doesn't work. 

### ISSUE THREAD

**Issue by ritankarsaha** [Priyaaa1/StartConnect-Hub#340]
**Describe the bug**
The google login / sign in button doesn't work. Clicking it just opens a new blank page. No authentication actually occurs

**To Reproduce**
1. Go to 'the website
2. Click on 'login
3. See error

**Expected behavior**
The google login/sign in thing actually appears. And the user can efficiently log in and sign in into the website.

**Screenshots**
<img width="1249" alt="Screenshot 2024-05-31 at 10 48 05 PM" src="https://github.com/Priyaaa1/StartConnect-Hub/assets/136831315/3819d48a-a928-47ad-bc22-d52f28ae5875">

<img width="541" alt="Screenshot 2024-05-31 at 10 47 28 PM" src="https://github.com/Priyaaa1/StartConnect-Hub/assets/136831315/a80241aa-8c84-44ef-8206-7c4ca2f9a1ae">

**Additional context**
The user gets a better user experience.

**Comment by ritankarsaha** [comment]
Please assign this issue to me under gssoc'24 . Also add the labels level and gssoc.

**Comment by drick-infinity** [comment]
can you assign this issue to me as I know how it work basiclly we use google auth for this I used in implies in various projects I have some example to dhoe you the google auth function here some example
![Screenshot (102)](https://github.com/Priyaaa1/StartConnect-Hub/assets/116994649/6e544d61-c2ac-4525-a4a5-ae06b5682263)

**Comment by drick-infinity** [comment]
under gssoc'24 level 3
