### ISSUE TITLE
Can add text as well in the number tab.

### ISSUE THREAD

**Issue by ritankarsaha** [Priyaaa1/StartConnect-Hub#341]
**Describe the bug**
Can type into the number tab as well.

**To Reproduce**
1. Go to 'website
2. Click on 'contact us
3. Scroll down to  type your name

**Expected behavior**
The contacts tab should incorporate only numbers not text

**Screenshots**
<img width="547" alt="Screenshot 2024-05-31 at 10 48 48 PM" src="https://github.com/Priyaaa1/StartConnect-Hub/assets/136831315/7fda79a9-60f9-4915-918b-6f72c17d2104">

**Additional context**
provides the user with a better UI

**Comment by Mansii8224** [comment]
Can you please assign me this task  I can do it well with better UI and responsive website?

**Comment by Priyaaa1** [comment]
@Mansii8224 the task is assigned to you, kindly complete it.

**Comment by Mansii8224** [comment]
Yes  , I am working on it as I know this task is assigned to me . Thank you

**Comment by Mansii8224** [comment]
That's fine @ritankarsaha
