### ISSUE TITLE
Responsiveness Of Contact Form

### ISSUE THREAD

**Issue by kashnx** [Priyaaa1/StartConnect-Hub#347]
![Screenshot_2024-06-01-04-20-02-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Priyaaa1/StartConnect-Hub/assets/148524648/37149da1-54b0-405a-a6d3-4aa6f87f48fb)

The Contact us component is not responsive for mobile view. I can fix it.

**Comment by Tanishka023** [comment]
Hey @Priyaaa1 I can fix this issue easily please assign this to me
