### ISSUE TITLE
Few Buttons Are Not Clickable and Page Not Responsive

### ISSUE THREAD

**Issue by sarthakmishra459** [Priyaaa1/StartConnect-Hub#35]
**Description**
Get Started button leads to nowhere and the the page doesn't fit to screen. On zooming out the page becomes unresponsive. I would like to fix the button not clickable issue and make page responsive.
**To Reproduce**
1. Go to landing page.
2. Click on Get Started button 
3. Zoom out the page
4. Scroll down to Contact section 
5. See error

**Expected behavior**
The button should have some functionality and Page should be responsive 

**Screenshots**
![Screenshot_2024-05-11-09-18-23-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Priyaaa1/StartConnect-Hub/assets/124512392/c25c81b3-3504-4498-8021-0f0271e22b9e)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [OnePlus Nord CE Lite 3]
 - OS: [Android]
 - Browser [Chrome]

**Comment by vinay02103** [comment]
I'd want to contribute to this project as a GSsoc'24 contributor. Please give me this assignment to work on.
