### ISSUE TITLE
Proper CSS of the login page

### ISSUE THREAD

**Issue by ctln23** [Priyaaa1/StartConnect-Hub#355]
**Describe the bug**
The Login and the Sign In with Google buttons on the Login page are not aligned propery.

**Expected behavior**
Proper alignment and spacing of the Login and the Sign In with Google buttons on the Login page.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/100524124/1e57ec94-331d-4e0b-a916-447a87103831)

@Priyaaa1 kindly assign this issue to me under gssoc '24

**Comment by Tanishka023** [comment]
Hey @Priyaaa1 I can fix this issue easily, please assign this to me

**Comment by Priyaaa1** [comment]
@Tanishka023 task will be assigned on the basis of first come first serve, if assignee doesn't complete the task within 3-4 days then this task will be assigned to you

**Comment by Tanishka023** [comment]
> @Tanishka023 task will be assigned on the basis of first come first serve, if assignee doesn't complete the task within 3-4 days then it will be assigned to you

Okay! @Priyaaa1

**Comment by drick-infinity** [comment]
can you assign this task to me as I learned MEN stack development I eager to make styling web page

**Comment by Harsha19-08** [comment]
@Priyaaa1 Now You can check this PR
