### ISSUE TITLE
Social Icons in footer are not Proper.

### ISSUE THREAD

**Issue by zalabhavy** [Priyaaa1/StartConnect-Hub#359]
**Describe the bug**
I want to improve social icons style in footer.

**Expected behavior**
They should proper style with effects and transitions.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/126322584/cb180b8d-b781-4b2d-803a-4c36700a40f6)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser Chrome

**Comment by Priyaaa1** [comment]
@zalabhavy the same issue has already been raised, kindly raise another issue
