### ISSUE TITLE
Improving the Footer Section

### ISSUE THREAD

**Issue by Prajwal1110** [Priyaaa1/StartConnect-Hub#372]
I would like to improve the footer section ,it looks so clumpsy and no proper alignment is done.
![os](https://github.com/Priyaaa1/StartConnect-Hub/assets/105029382/74de5027-0bac-4fe4-a5e3-c5ad3d940eba)

**Comment by Diwakar-Mishra** [comment]
I am a contributor to GSSOC'24 and would like to request the task of styling the footer section of your website. My goal is to ensure proper alignment and spacing between the components of the footer section to enhance the overall design and usability. 
 I am eager to contribute to the project's success So, please assign this task to me .

**Comment by Priyaaa1** [comment]
@Prajwal1110 this issue has already been raised. Kindly raise another issue.
