### ISSUE TITLE
Add Password toggling functionality

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Priyaaa1/StartConnect-Hub#375]
**Describe the solution you'd like**
I want to add a password toggling functionality so that user can hide or view the password on clicking on the eye button 

![Screenshot 2024-06-03 195946](https://github.com/Priyaaa1/StartConnect-Hub/assets/118350936/ba86d128-769d-4fe9-8077-77e99b1bbea7)

**Comment by Priyaaa1** [comment]
@Ayushmaanagarwal1211 any update?

**Comment by Ayushmaanagarwal1211** [comment]
Yes yes actually i was busy with my exam but tomorrow i have my last exam so will raise pr tomorrow sure

**Comment by UtkarshBirla28** [comment]
please assign this to me @Priyaaa1

**Comment by Priyaaa1** [comment]
@Ayushmaanagarwal1211 sorry, you have been given a lot of time to complete this task and you haven't completed it.

**Comment by Priyaaa1** [comment]
@UtkarshBirla28 kindly complete the task within 2 days.

**Comment by UtkarshBirla28** [comment]
> @UtkarshBirla28 kindly complete the task within 2 days.

Okayyy Thankyou!

**Comment by UtkarshBirla28** [comment]
@Priyaaa1  PR is done. Please check i have made some changes .
