### ISSUE TITLE
Adding a interactive FAQ section 

### ISSUE THREAD

**Issue by Devaki01** [Priyaaa1/StartConnect-Hub#38]
### Description
Many Websites have a section of "Frequently asked questions (FAQ's)" sections that highly contributes in improving user-experience. I would really love to contribute by adding and interactive and responsive FAQ section.  

### Proposed Functionality

- A FAQ section that display questions and their answers using accordion functionality.
- Users and view the answers of desired FAQ's by clicking on an arrow.

### Why add FAQ feature

- Improve your customer's experience.
-Provide quick information to help customers make a purchasing decision.
-Reduce the time your employees need to answer simple questions.

### About Me 
I am a tech-enthusiast, passionate about Front-end technologies such as React. As a GGSoC'24 contributor, I am eager to work on this functionality and promise to put all my efforts to deliver the best results.

**Comment by Devaki01** [comment]
Thank you for assigning it to me. Will start working on it immediately.

**Comment by Nkmeoo7** [comment]
@Priyaaa1 can you assign to me also i can fix this
