### ISSUE TITLE
Fixing of Login Page

### ISSUE THREAD

**Issue by nitin-pandita** [Priyaaa1/StartConnect-Hub#4]
The login page is overlapping the navbar
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/91310284/dcddac32-6bdd-42c2-a617-06ce2f6b51ad)
I can fix it please assing this to me

**Comment by Shyambarua** [comment]
Assign this issue to me.
As a full Stack Developer and 1 Year experience I can Write optimized code and Make it responsive.

**Comment by Sathya-reddy1658** [comment]
i can solve this and make it look much better

**Comment by Himanshityagii24** [comment]
I can solve this issue, as a Full stack developer I have experience of 2 years and have worked with login and signup pages in many projects, thus i can handle this very well.
