### ISSUE TITLE
No hover effect on x , LinkedIn and Instagram icon in footer

### ISSUE THREAD

**Issue by Prabhatyadav60** [Priyaaa1/StartConnect-Hub#402]
**Describe the bug**
The hover effect is not effectively functioning properly for the X, LinkedIn, and Instagram icons in the footer section of the website.

**To Reproduce**
1.Navigate to the website.
2.Scroll down to the footer section.
3.Hover over the X icon.
4.Hover over the LinkedIn icon.
5.Hover over the Instagram icon.
6.Observe that there is no good hover effect applied to these icons.

**Expected behavior**
The icons in the footer section should display a hover effect when hovered over, indicating their interactivity.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/133522303/181eab4c-461c-4c04-b6c5-da6f177be34b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser  : Brave ,Chrome 
 - Version : v1.66.118 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Prabhatyadav60** [comment]
@Priyaaa1 Kindly assign this to me , i can fix it .I am GSSoC'24  contributor.

**Comment by Shubhamsingh2110** [comment]
i would like to also work on this #402 under gssoc'24 contributor @Priyaaa1

**Comment by Priyaaa1** [comment]
@Prabhatyadav60 any update?
