### ISSUE TITLE
Add a favicon 

### ISSUE THREAD

**Issue by avanimathur** [Priyaaa1/StartConnect-Hub#41]
Description:
A favicon (favorite icon) depicts the identity of a particular website.
We can put the logo of this website as favicon.

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/151984867/26f6f230-c98e-433c-9a37-603f1d77c68a)

This contribution is under GSSOC'24.

**Comment by avanimathur** [comment]
Please assign it to me
Thanks

**Comment by Stacvirus** [comment]
hey can I start working on this ?
