### ISSUE TITLE
Addition of Chatbot

### ISSUE THREAD

**Issue by Anjaliavv51** [Priyaaa1/StartConnect-Hub#415]
**Is your feature request related to a problem? Please describe.**
No , Addition of Chatbot assistant.

**Additional context**

PLease assign me this issue under GSSOC.

**Comment by Anjaliavv51** [comment]
@Priyaaa1 please assign me this issue under GSSOC

**Comment by Priyaaa1** [comment]
@Anjaliavv51 chatbot is already there
