### ISSUE TITLE
Bug : Website not visible

### ISSUE THREAD

**Issue by Priyaaa1** [Priyaaa1/StartConnect-Hub#418]
**Describe the bug**
When clicking the website link, people are unable to see the website because of some error in the package.json

**To Reproduce**
1. Go to 'website'
2. See error

**Expected behavior**
On clicking the website link, website should be visible.

**Screenshots**

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/105431748/2d0ce0b8-33d0-4e70-9389-b5f71e13fa35)

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/105431748/0f9eac90-223f-47f0-9895-b22ae95056f9)

**Desktop (please complete the following information):**

**Additional context**
Contributors can resolve this issue :)

**Comment by codewithmurali** [comment]
@Priyaaa1 Assign this to me let me fix it

**Comment by rohitroy-github** [comment]
@codewithmurali is it done ?

**Comment by codewithmurali** [comment]
@rohitroy-github there is a dependency conflict with react-google-login due to the version of React being used in your project. The error indicates that react-google-login requires React version ^16 || ^17, but this project is using React version 18.3.1,

Will I force to install the dependencies? or there are some alternative react-google-button?

**Comment by rohitroy-github** [comment]
@codewithmurali Yeah, I checked the issue. I think we should stick with the react-google-button alternative. Force installing dependencies can cause issues with others in the codebase. [ react-google-login ] has also been deprecated >>> [Link](https://www.npmjs.com/package/react-google-login). 

Also just add in the createContext, it will solve the issue. 

@Priyaaa1 what's your take on this ? I tried resolving the issue by using a previous commit and it worked so do you wanna revert back or should @codewithmurali make the changes ? Please instruct her accordingly.

**Comment by rohitroy-github** [comment]
@codewithmurali please wait for the approval before making any PR.

**Comment by Priyaaa1** [comment]
@rohitroy-github yeah I think @codewithmurali should go with the react-google-button, it would be better rather than force installing dependencies

**Comment by codewithmurali** [comment]
@rohitroy-github No need for react-google-button, Our project is already using the @react-oauth/google package in our sign-up page, we can use the same package for the login page as well. 

@Priyaaa1 Okay, Let me fix it.

**Comment by rohitroy-github** [comment]
The site's working on localhost on my end now. Good work @codewithmurali ⭐

**Comment by codewithmurali** [comment]
> The site's working on localhost on my end now. Good work @codewithmurali ⭐

Thank you @rohitroy-github
