### ISSUE TITLE
[Bug]: Footer Re-Design

### ISSUE THREAD

**Issue by ManishBirthlia** [Priyaaa1/StartConnect-Hub#429]
**Describe the bug**
The footer should be responsive to different resolutions and everything in the way left.

**To Reproduce**
1. Go to [home](https://startconnect-hub.netlify.app/)
2. Scroll down to Footer
3. See error

**Expected behavior**
The footer should be responsive to different resolutions and everything in the way left

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/96776615/e8cb894a-1d17-440e-99b0-e2615b328d35)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser:  Chrome
 - Version: 22

**Smartphone (please complete the following information):**
 - Device: PocoX3 Pro
 - OS: Android 12
 - Browser: Chrome
 - Version: 22

**Additional context**

**Comment by ManishBirthlia** [comment]
@Priyaaa1 Assign me this issue please

**Comment by Riyasharma1311** [comment]
please assign me this issue
