### ISSUE TITLE
Dark Mode toggle feature

### ISSUE THREAD

**Issue by maverickcodex18** [Priyaaa1/StartConnect-Hub#44]
mentor @Priyaaa1

**Is your feature request related to a problem? Please describe.**
Most of the users/developers are frustrated by continues use of browser in light mode , enabling the dark mode feature might enhance user interaction and satisfaction.

**Describe the solution you'd like**
A toggle to switch between light and dark modes
Kindly assign me this task under **GSSoC'24 project**

**Additional context**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/79051168/b528e44a-53e8-4e39-9605-2f31d90e866b)

**Comment by vinay02103** [comment]
Hi, Mentor,I would want to work under Gssoc 24 on this issue. Could you please give me this?

**Comment by Khizarshah01** [comment]
@maverickcodex18 I think you have some misunderstanding, I am not the mentor or admin of the repo. If you need to work on this issue, ask @Priyaaa1 to assign you.

**Comment by maverickcodex18** [comment]
> @maverickcodex18 I think you have some misunderstanding, I am not the mentor or admin of the repo. If you need to work on this issue, ask @Priyaaa1 to assign you.

Apologies, thanks for letting me know

**Comment by sachinGurjar17** [comment]
@Priyaaa1 , please assign this issue to me

**Comment by Jamir2412** [comment]
@maverickcodex18 can you assign this issue to me..?

**Comment by sdass1918** [comment]
Hey please assign me this task! I want to work on this issue

**Comment by drick-infinity** [comment]
Assign this issue to me As learned MERN full stack development I easily apply the code for dark and light theme also

**Comment by MrudulaTeegala** [comment]
@Priyaaa1 Kindly assign this issue to me

**Comment by Rv43** [comment]
Can you assign this issue to me I want to work on this issue pls

**Comment by Yuvraj960** [comment]
@Priyaaa1 Please assign this issue to me under GSSoC24

**Comment by Hemxnt** [comment]
assign me this issue

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .
