### ISSUE TITLE
💡Add a Feedback Form/Page to "Star Connect Hub" Website

### ISSUE THREAD

**Issue by MastanSayyad** [Priyaaa1/StartConnect-Hub#444]
Hey @Priyaaa1 

I would like to add a **feedback form/page**

### Use Case
- User: Clicks on the "Give Feedback" button.
- System: Displays the feedback form as a popup.
- User: Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- User: Clicks the "Submit" button on the form.
- System: Displays a confirmation message indicating the feedback was submitted successfully.
- User: Closes the feedback form popup.

To improve user experience and gather valuable insights from visitors, i suggest to add a feedback form/page to the "Star Connect Hub" website. This form will allow users to provide their opinions, report issues, and suggest improvements directly.
- **For example like this:**

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/101971980/6f2a75eb-41dc-4e30-942f-02aa8798c419)

Please assign this issue to me.

**Comment by MastanSayyad** [comment]
@Priyaaa1 pls assign this issue to me.

**Comment by MastanSayyad** [comment]
Hey @Priyaaa1 On which email id should the feedback be sent??

**Comment by Priyaaa1** [comment]
@MastanSayyad email: maheshwaribasu4@gmail.com
