### ISSUE TITLE
scroll progress bar missing

### ISSUE THREAD

**Issue by paulkrishanu4** [Priyaaa1/StartConnect-Hub#446]
this website should have a scroll progress bar
like this

https://github.com/Priyaaa1/StartConnect-Hub/assets/169196836/e619315b-b250-4769-84c5-fa3867aab7ca

Assign me under gssoc

**Comment by MastanSayyad** [comment]
@Priyaaa1 i think the issue is not resolved yet, and the PR is also closed, i would likw to take on this task, could you please assign me this issue?
