### ISSUE TITLE
Add a Hover  Functionality in Contat us

### ISSUE THREAD

**Issue by jayraj175coder** [Priyaaa1/StartConnect-Hub#45]
![Screenshot 2024-05-11 151114](https://github.com/Priyaaa1/StartConnect-Hub/assets/135996214/8a9d0947-c467-409f-9303-64589372c5e9)
This one is page , After click on contact us it does not show effect.
COuld yo assign this me under gssoc24.??

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.
