### ISSUE TITLE
Automated Greetings on Issue Raised

### ISSUE THREAD

**Issue by thevijayshankersharma** [Priyaaa1/StartConnect-Hub#458]
**Is your feature request related to a problem? Please describe.**
Contributors often lack immediate acknowledgment when they raise an issue in the project repository, leading to a sense of disconnection and uncertainty about whether their concern has been noticed.

**Describe the solution you'd like**
Implement an automated system that generates a friendly greeting message whenever a new issue is raised within the project repository, providing immediate acknowledgment to the contributor.

**Additional context**
This feature would enhance user experience by fostering a sense of inclusivity and responsiveness within the project community. It would ensure that contributors feel valued and engaged from the moment they raise an issue, ultimately contributing to a more positive and collaborative development environment.

**Comment by Priyaaa1** [comment]
@thevijayshankersharma this feature has been implemented, kindly raise another issue.

**Comment by thevijayshankersharma** [comment]
@Priyaaa1 I can make auto greeting on PR, or issue or PR closed. should i raise for them ?
