### ISSUE TITLE
📝[Docs]: Update Twitter logo with X 

### ISSUE THREAD

**Issue by Braj-01** [Priyaaa1/StartConnect-Hub#459]
**What Docs changes are you proposing?**
Provide a clear description of the changes you're proposing for the documentation. Are you suggesting corrections, clarifications, additions, or updates?

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
Explain the motivation behind the proposed changes and how they will benefit the community or users of the documentation.

**Describe the solution you'd like**
Provide a clear and concise description of the changes you'd like to see implemented in the documentation.

**Describe alternatives you've considered**
If you've thought about alternative approaches or solutions, briefly describe them here.

**Additional context**
Add any additional context, examples, or screenshots related to the proposed documentation changes.

**Comment by Braj-01** [comment]
@Priyaaa1 Pls add level 1 label to the issue.

**Comment by Priyaaa1** [comment]
@Braj-01 it's a small task so I can't give this issue level1 label. By gssoc label you'll get 1 point.

**Comment by Braj-01** [comment]
Ok

**Comment by UtkarshBirla28** [comment]
Hello ! please assign this to me i will work on it 
@Braj-01

**Comment by jayanththalla** [comment]
please assign me @pa
i will add the description of the project

**Comment by Priyaaa1** [comment]
@UtkarshBirla28 @jayanththalla @Braj-01 this issue has been resolved.
