### ISSUE TITLE
Change hover of navbar..

### ISSUE THREAD

**Issue by jayraj175coder** [Priyaaa1/StartConnect-Hub#46]

**Comment by jayraj175coder** [comment]
Here your navaigation does not  attract anyone come here. I want to change it.
Could you assign this issue under gsoc??
![Screenshot 2024-05-11 151205](https://github.com/Priyaaa1/StartConnect-Hub/assets/135996214/9990485c-9702-4e43-a57b-c1bc88c57742)

**Comment by Manaswini123456** [comment]
Kindly, assign me with this issue, I am willing to connect and contribute my solution too.

**Comment by SanaAzeem512** [comment]
please assign me this issue ..

**Comment by jayraj175coder** [comment]
@Priyaaa1 , #46 issue solved.

**Comment by Priyatosh11** [comment]
Here, I can change the Navbar ui design and make it more attractive, Can you please assign me the issue???

**Comment by thecloudcode** [comment]
Hi, @Priyaaa1 I would love to work on this issue, as it one of such issues I have worked earlier on as well. Kindly, assign me this issue.

**Comment by Priyaaa1** [comment]
@Manaswini123456 @SanaAzeem512 @Priyatosh11  anyone of you want to work on this issue?

**Comment by Priyaaa1** [comment]
@thecloudcode the task will be assigned on the basis of first come first serve. If the assignee will not complete the task within 2-3 days, it will be assigned to you

**Comment by Manaswini123456** [comment]
@Priyaaa1 Please assign me with this issue, I would like to work upon it.

**Comment by thecloudcode** [comment]
@Priyaaa1 sure mam

**Comment by sanchitkhthpalia** [comment]
**Please assign this issue to me under GSSOC'24.**

**Comment by Manaswini123456** [comment]
@Priyaaa1 Will surely provide my insights. Thank you.
