### ISSUE TITLE
Add Hover effects on Scrollbar so when user can  experience that he/she hold scrollbar

### ISSUE THREAD

**Issue by zalabhavy** [Priyaaa1/StartConnect-Hub#462]
**Is your feature request related to a problem? Please describe.**
When user hold scrollbar that time user can't get feel.
But if we provide hover effects so user can feel that.

**Describe the solution you'd like**
I will simple add hover effects in css hover color should be dark than normal.

**Comment by zalabhavy** [comment]
@Priyaaa1 can you please assign me this task.

**Comment by Priyaaa1** [comment]
@zalabhavy the issue for this has already been raised (#446). Kindly do not raise same issue if it's already there.
