### ISSUE TITLE
[Bug] : Navbar is not responsive

### ISSUE THREAD

**Issue by Priyaaa1** [Priyaaa1/StartConnect-Hub#469]
**Describe the bug**
The navbar of the website is not responsive.

**Expected behavior**
It must be responsive for the small screens too.

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/105431748/01cb7871-b11e-4dac-93ac-b02d057a4c5d)

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/105431748/89efee7d-c81d-48bf-804e-3b8fb526fd40)

**Desktop (please complete the following information):**

**Comment by ManishBirthlia** [comment]
@Priyaaa1 okay i will work on this issues along with one other
