### ISSUE TITLE
Logo and Home overlapping in nav bar

### ISSUE THREAD

**Issue by harsh02mishra** [Priyaaa1/StartConnect-Hub#471]
**Describe the bug**
The website logo overlaps with the home button in the nav bar.

**Expected behavior**
I want to separate them by providing margin between them.

**Screenshots**

![Overlaps](https://github.com/Priyaaa1/StartConnect-Hub/assets/144336311/20034989-e498-4ff7-91ea-4b6a8af523ba)

**Comment by Priyaaa1** [comment]
@harsh02mishra this has been resolved. Kindly raise any other issue.
