### ISSUE TITLE
Add Sign-Up and Login Page with Multiple Options

### ISSUE THREAD

**Issue by revanth1718** [Priyaaa1/StartConnect-Hub#476]
I propose adding a new feature to the repository: a modern, user-friendly sign-up and login page. This page will enhance user experience by providing a seamless interface for account creation and authentication, including various sign-in options such as social media accounts.
![sign up](https://github.com/Priyaaa1/StartConnect-Hub/assets/109272714/9e5b3b23-a912-48c6-b49a-a27ab9cc561d)

**Comment by Priyaaa1** [comment]
@revanth1718 someone is already working on this. Kindly raise some other issue.

**Comment by Priyaaa1** [comment]
@revanth1718 you can improve that page after the issue #335 gets resolved.

**Comment by Priyaaa1** [comment]
@revanth1718 the task has been assigned to you, as the contributor doing it couldn't resolved the conflicts. Kindly complete it within 3-4 days.

**Comment by revanth1718** [comment]
ok mam

**Comment by RamakrushnaBiswal** [comment]
hi @Priyaaa1 can i work upon the issue

**Comment by Rajput-xv** [comment]
Hello, @Priyaaa1 
as this issue is yet to resolve
i would like to work on this and i can do it asap.

**Comment by Priyaaa1** [comment]
@revanth1718 any update?

**Comment by revanth1718** [comment]
i will submit within 3 days mam

**Comment by Priyaaa1** [comment]
@revanth1718 okay
