### ISSUE TITLE
Dark/Light toggle mode button not visible

### ISSUE THREAD

**Issue by mehrun171** [Priyaaa1/StartConnect-Hub#480]
**Is your feature request related to a problem? Please describe.**
toggle mode button is not visible

**Describe the solution you'd like**
simple toggle button to change to light theme / dark theme vice versa based on user preferences to help them have best experience while using the application 
even if it exists it is not visible...hence changes need to be done

![Screenshot 2024-06-16 001004](https://github.com/Priyaaa1/StartConnect-Hub/assets/116735695/29ce8531-aa1b-4f58-ba2b-997a87128931)

**Additional context**

**Comment by mehrun171** [comment]
Please assign me this issue @Priyaaa1

**Comment by Priyaaa1** [comment]
@mehrun171 it is visible now. Kindly raise some other issue.
