### ISSUE TITLE
Add hover over effects to buttons

### ISSUE THREAD

**Issue by mehrun171** [Priyaaa1/StartConnect-Hub#481]
when clicking button the user has to identify that he is clicking the button
therefore adding of hover over effects will give the user sign of clicking on the button which can give the user Best UI experience 

![Screenshot 2024-06-16 001335](https://github.com/Priyaaa1/StartConnect-Hub/assets/116735695/ba7a832b-f1c6-4275-9531-619a5849f02c)

**Comment by Riyasharma1311** [comment]
please assign me this issue.

**Comment by imvish21** [comment]
@Priyaaa1  Can you assign this issue to me?

**Comment by Priyaaa1** [comment]
@mehrun171 @imvish21 @Riyasharma1311  this has been already done.
