### ISSUE TITLE
Feature improvements needed

### ISSUE THREAD

**Issue by dsaikiran01** [Priyaaa1/StartConnect-Hub#484]
I found the testimonials text to be not visible when hovered 
Also the side buttons of the testimonials sections have no hovering effects
 
![Screenshot (258)](https://github.com/Priyaaa1/StartConnect-Hub/assets/108150261/40b86dbd-9d7c-405d-854d-594f80918f5b)

I want to work on these issues and fix them
Please assign me this issue under GSSoC'24

**Comment by urgetolearn** [comment]
Hey @Priyaaa1 Can I work on this issue??

**Comment by dsaikiran01** [comment]
These features have been fixed by someone. I was too late to fix that, so closing the issue.
