### ISSUE TITLE
[Bug] : Fix the Hamburger menu

### ISSUE THREAD

**Issue by Priyaaa1** [Priyaaa1/StartConnect-Hub#486]
**Describe the bug**
When we click on the Hamburger Menu button, the drop down list appears which is not looking good. It affects user experience.
Also, the drop down list closes only when the Hamburger Menu button is clicked. 

**To Reproduce**
1. Go to 'website'
2. Reduce window size
3. Click on 'Hamburger menu button'

**Expected behavior**
On clicking the Hamburger Menu button the drop down must be matching with the website theme, and the text should be clearly visible. Also the drop down menu should close on clicking anywhere other than that menu. 

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/105431748/4ddbe206-9c10-4fa8-8d35-042b62ed841f)

**Desktop (please complete the following information):**

**Comment by pani2004** [comment]
@Priyaaa1 I would like to work on this

**Comment by pani2004** [comment]
@Priyaaa1 I would like to work on this
