### ISSUE TITLE
Feature : Adding Discord and WhatsApp community at the footer

### ISSUE THREAD

**Issue by GAVINESHWAR** [Priyaaa1/StartConnect-Hub#492]
**Is your feature request related to a problem? Please describe.**
In the footer section Discord is not available and whatsApp community link also can be added .

**Describe the solution you'd like**

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/124431955/a39ecf12-a5c1-466c-8bbb-074568e5cc43)
here we can add those ones.

In the footer discord is missing and we can add discord for making connections, community and it reach to huge people along with that we can also add the WhatsApp community link as well for the better reach newly started idea.

**Additional context**

Assign me this issue @Priyaaa1 mam to make contribution to the project

Thank you

**Comment by Priyaaa1** [comment]
@GAVINESHWAR i don't think it's needed now. Kindly raise some other issue.
