### ISSUE TITLE
Add error 404 page.

### ISSUE THREAD

**Issue by taneeshaa15** [Priyaaa1/StartConnect-Hub#502]
**Is your feature request related to a problem? Please describe.**
Users often faces problem when they mistakenly type wrong URL or broken links, to avoid this problem error 404 page is required.

**Describe the solution you'd like**
I will add error 404 page so that the user will be directly redirected to home page without taking much time.

**Additional context**
![md](https://github.com/Priyaaa1/StartConnect-Hub/assets/157527085/f7723aaf-5ff4-43f3-a1f8-0320c658cbed)
It will somehow look like this but not exactly like this, also redirection to homepage feature will be added.

**Comment by taneeshaa15** [comment]
@Priyaaa1 Please assign this issue to me under gssoc'24 with suitable level labels.

**Comment by Priyaaa1** [comment]
@taneeshaa15 this page is already there.
