### ISSUE TITLE
Dropdown of Navbar not visible in mobile screen ✨

### ISSUE THREAD

**Issue by Utsavladia** [Priyaaa1/StartConnect-Hub#508]
**Describe the bug**

**To Reproduce**
1. Go to mobile view in inspect
2. Click on menu button

**Expected behavior**
It should be visible on mobile screen to use navigation properly

**Screenshots**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/124615886/66abc4bd-95d9-4772-b64f-7ff303eb7841)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I would love to contribute to this project...

**Comment by Priyaaa1** [comment]
@Utsavladia this issue has been resolved. Kindly raise some other issue.
