### ISSUE TITLE
Routing is not working on clicking in Mobile view....

### ISSUE THREAD

**Issue by Utsavladia** [Priyaaa1/StartConnect-Hub#510]
**Is your feature request related to a problem? Please describe.**
The link to different sections in navbar is not working in mobile view

**Describe the solution you'd like**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/124615886/dd555ac7-84e3-40cb-bce7-d2c8bb6e4a6e)

**Additional context**
I would love to contribute to this project

**Comment by Priyaaa1** [comment]
@Utsavladia this issue has been resolved now. Kindly raise some other issue.
