### ISSUE TITLE
The feedback form is not responsive at all

### ISSUE THREAD

**Issue by r7projects-shayan** [Priyaaa1/StartConnect-Hub#524]
**Describe the bug**
The feedback form is not responsive for devices smaller than desktop and tvs

**To Reproduce**
1. Go to the website
2. Click on Inspect element or press f12
3. Scroll down to footer
4. Go to feedback
5. Reduce the dimensions to mobiles or tablets
6. See error

**Expected behavior**
The feedback form should be responsive for all devices and dimensions

**Screenshots**
![Screenshot 2024-06-21 223751](https://github.com/Priyaaa1/StartConnect-Hub/assets/167475552/1dd252d4-3942-4057-a159-14f25ac58fd7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Microsoft Edge
 - Version: 2H22

**Smartphone (please complete the following information):**
 - Device: Iphone XR, Iphone SE, Samsung Galaxy, One Plus

**Additional context**

**Comment by r7projects-shayan** [comment]
@Priyaaa1 kindly assign me this issue so that i can fix it soon

**Comment by Priyaaa1** [comment]
@r7projects-shayan the same issue has been raised already and someone is working on it. Kindly do not raise same issue again and again. you can comment there if you want to work on this.
