### ISSUE TITLE
ensuring valid email id is entered and password has the see/unsee icon with minimum length

### ISSUE THREAD

**Issue by sayalisachin** [Priyaaa1/StartConnect-Hub#53]
**Feature Request Related To EMAIL & Password**
The Email ID and Password cannot be checked if it is valid/of minimum length. This can result in too many entries in the databse in fututre.

**Describe the solution you'd like**
Email Id Verfication to be enabled-  if the email id entered by user is valid or not. Password can have the see/unsee feature and can be set to minimum characters.

Can I please be assigned to sort this issue?
(GSSoC Contributor)

**Comment by sayalisachin** [comment]
Can I please be assigned to sort this issue?
(GSSoC Contributor

**Comment by kajolchatt** [comment]
Hi @Priyaaa1  could you please assign this issue to me?

**Comment by Priyaaa1** [comment]
@sayalisachin Kindly make changes within 2 days, otherwise this task will be given to someone else.

**Comment by sayalisachin** [comment]
> @sayalisachin Kindly make changes within 2 days, otherwise this task will be given to someone else.

yes, thank you so much!

> @sayalisachin Kindly make changes within 2 days, otherwise this task will be given to someone else.

yes, will surely do, thank you so much!

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue, Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!

**Comment by sayalisachin** [comment]
@Priyaaa1 , #53 issue solved. Please review my pull request. Thank you so much!
