### ISSUE TITLE
Footer Links Do Not Scroll to Sections When Accessed from Different Routes

### ISSUE THREAD

**Issue by pani2004** [Priyaaa1/StartConnect-Hub#536]
**Describe the bug**
When accessing the footer links on the Privacy Policy page (or any other page) and clicking on links such as Testimonials, the page does not scroll to the respective section 

https://github.com/Priyaaa1/StartConnect-Hub/assets/154724111/fb375aa2-d0c5-4986-b63e-10ecd450eb5a

**Comment by pani2004** [comment]
@Priyaaa1 can I work on this?

**Comment by Priyaaa1** [comment]
@pani2004 yes sure
