### ISSUE TITLE
Adding feedback form

### ISSUE THREAD

**Issue by harinisayani** [Priyaaa1/StartConnect-Hub#538]
**Is your feature request related to a problem? Please describe.**
I observed that there is no feedback form in the webpage.

**Describe the solution you'd like**
I want to add it in webpage.

**Additional context**
I am GSSOC'24 Contributor.
Please assign me this task.

**Comment by Priyaaa1** [comment]
@harinisayani the feedback page is already there in the website. Kindly raise some other issue.
