### ISSUE TITLE
Adding functionality in mobile, gmail section. Addition of functional login/signup page. Improvement in NavBar, Footer.

### ISSUE THREAD

**Issue by Rajput-xv** [Priyaaa1/StartConnect-Hub#55]
Problems :-

1. Links/Redirecting should be present in logo and other items in nav.
2. the current active page to user should be visible in navbar, some indications.
3. Footer section need upgrades.
4. if any gmail, mobile number is clicked then it should redirect to specific application to proceed further.
5. I would like to add fully functional login signup page.

if u would assign these to me, then i would like to resolve these issues.
@Priyaaa1

**Comment by SanaAzeem512** [comment]
please assign this issue to me under GSSOC24
