### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [Priyaaa1/StartConnect-Hub#552]
Hey @Priyaaa1 ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Screenshot(Mandatory):

![343046177-a64505c3-c4e1-432e-bd29-29228d4ab763](https://github.com/Priyaaa1/StartConnect-Hub/assets/129590267/7367b712-88d5-48cf-9565-4f4cf75d2c02)

@Priyaaa1 ,Could you please assign me this issue under gssoc'24 ?

Are you contributing under any open-source program ?
GSSOC'24

**Comment by Priyaaa1** [comment]
@TheNikhilRaj this feature of scroll to top button is already there in the website. Kindly go through the website and then raise issue.

**Comment by TheNikhilRaj** [comment]
@Priyaaa1 ohh sorry i didn't see it's on left side on the page!
