### ISSUE TITLE
BUG: Services Page has hover Error

### ISSUE THREAD

**Issue by MuraliDharan7** [Priyaaa1/StartConnect-Hub#559]
**Describe the bug**

In the services page, when I hover over the services section the section changing to black.

**To Reproduce**
1. Go to 'Login page and login'
2. Click on 'services'
3. Scroll down to 'a bit'

**Expected behavior**
The hover should be pop up the section or has clear hover effect. 

**Screenshots**

https://github.com/Priyaaa1/StartConnect-Hub/assets/130668745/17651cca-81fc-40b6-9dc7-6121543a67a2

**Comment by Priyaaa1** [comment]
@MuraliDharan7 it has been resolved now
