### ISSUE TITLE
Add Website Description in Footer 

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Priyaaa1/StartConnect-Hub#562]
Hey @Priyaaa1 

I would like to add website description to look footer more complete.

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/163530398/735cb749-17a8-41b3-b368-9279a649b794)

Could you please assign this issue to me under GSSOC24 ?

**Comment by ishikajain1234** [comment]
i would like to contribute on this project. plz assign to me

**Comment by RadhikaMalpani1702** [comment]
@Priyaaa1  Please assign this issue to me.

**Comment by Priyaaa1** [comment]
@RadhikaMalpani1702 that space has been covered by visitors count
