### ISSUE TITLE
➕Implement Real Email-Sending Functionality for Feedback Page !

### ISSUE THREAD

**Issue by aslams2020** [Priyaaa1/StartConnect-Hub#569]
Hello @Priyaaa1,

In the previous implementation #553,  the feedback submission form was showing a pop-up confirmation message **before the email was actually sent.**  
@Priyaaa1 , You pointed out that **the confirmation should only appear after the email has been successfully sent.**

### The Solution and Implementation:
I have implemented a real email-sending functionality using the **"emailjs-com"** library. This ensures that the success message is displayed only after the feedback email has been successfully sent.

#### Here's what I did:
- Integrated the **"emailjs-com" library** to handle email sending.
- Modified the feedback form **to send an email using "EmailJS" instead of opening the local mail application.**
- Updated the code to **display the success pop-up** message **only after the email is sent**.

You can see the implementation in the demo video attached.

https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/aa80859b-74d0-4d84-9879-e1b31ff88507

After that, Check The Mail On Given EmailId(for now it's my email id)
(For those Orange Circles, Please Read "Next Steps" Below )

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/6ab7b23f-5d6f-43f3-9907-864da7be9042)

<hr> 

### Next Steps:
Please review the demo and let me know if everything is okay. (if not please tell me I'll improve that)

If approved, **I'll need your EmailJS "Service_ID", "Template_ID", and "User_ID"** to complete the final setup. 
This will allow me **to update the template to use your project's official email [startconnecthub@gmail.com]** 
**(NOTE : I will not have access to it; full access will be given to you.)**

### Steps to Provide EmailJS Credentials to me :
1. Create a free account on EmailJS (if you don't have one). [Link to EmailJs](https://www.emailjs.com/) 
2. Set up a new email service and **get the Service_ID.**
3. Create an email template for the feedback form and **get the Template_ID.** (see example below)
' ' '
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/0b4701b6-cea8-4a1b-888c-993f54ad94a2)
> 💡Circle (1)  On Right Side **(To Email)**
        - Enter the official email id of the star connect [startconnecthub@gmail.com].
> 💡Circle (2) On Right Side **(From Name)**
        - Enter "Star Connect Team" (for ex.) 

- And in other underlined places, Please keep it as I provided in the Screenshot. (**As they are the ID's from the code**)
' ' '

4. **Get your User_ID** from your EmailJS dashboard.

At the End - **Please Share these credentials with me so that I can update the code to use them.**

<hr> 

After that, Please merge that PR. I've gone through Many Official Documentations to Implement this Solution.
@Priyaaa1, Thank you for cooperating!

**Comment by aslams2020** [comment]
@Priyaaa1 I hope i was able to explain it to you.

**Comment by Priyaaa1** [comment]
@aslams2020 wait, I'll look at this in 1-2 days. I'm busy right now.

**Comment by aslams2020** [comment]
> @aslams2020 wait, I'll look at this in 1-2 days. I'm busy right now.

Ohkay Got it, thanks!

**Comment by aslams2020** [comment]
@Priyaaa1 Thankyou for assigning the task.
Please provide me the necessary ID's following the steps given above. 
Then I will send the PR request.

**Comment by Priyaaa1** [comment]
@aslams2020 
**service id:** service_d7vmj7d
**template id:** template_lis1bcj
**public key:** DsYw9p-_g9F5DotTc

**Comment by Priyaaa1** [comment]
@aslams2020 
**service id :** service_7ifnpdc
**template id :** template_lwovuy9
**public key :** mFZbq2zn7d1nHMIYM

**Comment by aslams2020** [comment]
> @aslams2020 **service id :** service_7ifnpdc **template id :** template_lwovuy9 **public key :** mFZbq2zn7d1nHMIYM

@Priyaaa1 Done. Please check
