### ISSUE TITLE
Enhance the contact page - as it has inconsistent spacing

### ISSUE THREAD

**Issue by ananyag309** [Priyaaa1/StartConnect-Hub#572]
![incosistent](https://github.com/Priyaaa1/StartConnect-Hub/assets/145869907/5ea1bd2e-b994-4eb1-8ab8-2de702b4fe22)

The current contact page lacks professional styling and has cluttered elements that reduce its visual appeal. Enhancing the page involves adding more styling and proper spacing to create a clean, organized layout while maintaining the existing interface. This will improve readability and provide a more polished and professional appearance.

i would like to contribute to the project if needed under gssoc

**Comment by riyasaxena32** [comment]
please assign me this issue to me under gssoc 24
i will complete it very soon
