### ISSUE TITLE
Add padding to contact us

### ISSUE THREAD

**Issue by srilekha279** [Priyaaa1/StartConnect-Hub#574]
**Describe the bug**
The contact us page in dark mode is not looking good. I attached the screenshot as follows.

**Expected behavior**
Adding padding around the contact us form improves user experience

**Screenshots**
![Screenshot (724)](https://github.com/Priyaaa1/StartConnect-Hub/assets/158455553/41213aa3-0716-4ae6-b978-bc9bbc8d135a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Priyaaa1** [comment]
@srilekha279 this issue has already been raised. Kindly raise some other issue.
