### ISSUE TITLE
Feat : Add Email Field to Contact Us Page

### ISSUE THREAD

**Issue by HarshadaGirase** [Priyaaa1/StartConnect-Hub#578]
**Description**

Enhance the Contact Us page by adding an email field to collect email addresses from users. This will provide an additional contact method, improve customer communication, and allow for more efficient follow-up.

![emailfield](https://github.com/Priyaaa1/StartConnect-Hub/assets/128895955/972a5927-0004-4a87-9657-49d83663d33e)

**Comment by HarshadaGirase** [comment]
I would like to work on this. Kindly assign to me.

**Comment by ishikajain1234** [comment]
i would like to contribute on this project. plz assign to me
