### ISSUE TITLE
The dark mode is not working properly

### ISSUE THREAD

**Issue by JagjeetChauhan** [Priyaaa1/StartConnect-Hub#581]
**Describe the bug**
The dark mode is only covering a particular section of the home page 

**Screenshots**
Dark Mode: 
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/98844703/9780571d-294f-4c8b-9357-d93c65442d3c)
Light mode:
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/98844703/68a4cb1d-e826-402c-919f-6dc29796cdda)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version:- 
Kindly assign this task to me under GSSOC'24

**Comment by Priyaaa1** [comment]
@JagjeetChauhan the issue has been resolved now
