### ISSUE TITLE
feat: implementing google maps 

### ISSUE THREAD

**Issue by reshamsai150** [Priyaaa1/StartConnect-Hub#583]
**Is your feature request related to a problem? Please describe.**
 Adding Google Maps to your web page can enhance user experience and provide valuable location-based information.
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/164533685/759c33d9-ca75-44c7-bbcb-c2fca4916e2f)

**Comment by Priyaaa1** [comment]
@reshamsai150 it is not needed now, kindly raise some other issue.
