### ISSUE TITLE
unable to access social media profiles.

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Priyaaa1/StartConnect-Hub#584]
![Screenshot (1387)](https://github.com/Priyaaa1/StartConnect-Hub/assets/117037441/53e6ab8f-54f5-4e29-b5b8-eca174abe1d9)
while clicking on the linkedin icon in the footer section , it is unable to access ur linkedin profile. I can amend this .
even ur instagram is not working .
![Screenshot (1388)](https://github.com/Priyaaa1/StartConnect-Hub/assets/117037441/d6a19eb3-d027-4d91-b140-9d5ceffcd7eb)
 i think if u do not want to make ur accounts public then u should remove these  icons from the project as well as they only increase the liability.
@Priyaaa1  kindly assign me this issue under gssoc'24

**Comment by riyasaxena32** [comment]
please assign me this issue to me under gssoc 24
i will complete it very soon
