### ISSUE TITLE
Feature; Add Rate Us Modal/Page

### ISSUE THREAD

**Issue by MuraliDharan7** [Priyaaa1/StartConnect-Hub#585]
**Is your feature request related to a problem? Please describe.**
When ever there is a website, which gives very optimal solution to users there should be rateus page where the users can give feedback and review about the product.

**Describe the solution you'd like**
I would like to add Rateus page which has rating system and feedback.

**Additional context**
Assign me under GSSoC'24.

**Comment by Priyaaa1** [comment]
@MuraliDharan7 there is feedback page in the website in which users can rate the website.
