### ISSUE TITLE
[Fix] Log in and Sign Up page styling GSSOC 2024 Good First Issue

### ISSUE THREAD

**Issue by abir446** [Priyaaa1/StartConnect-Hub#6]
<h1>**Both Log in and Sign Up pages not using full height**</h1> under Gssoc 2024

<h2>What can I do? </h2>
<p>I can fix both the pages and, there is a problem that, the **Navbar** component is slightly visible. I want to keep the navbar prominent in both the pages as it will help in navigation. Also, I can fix the styling of **both log in and sign up** pages.</p>

<span>Also it would be helpful if we are permitted to use **Tailwind CSS**, else vanilla CSS would also be fine</span>

<p>I would be obliged to get the opportunity to fix the issue.</p>

**Comment by Shyambarua** [comment]
Assign this issue to me.
As a full Stack Developer and 1 Year experience I can Write optimized code and Make it responsive.

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me ?

**Comment by SadafKausar2025** [comment]
Please Assign this issue to me. I will fix it

**Comment by ivarcodes** [comment]
i would love to work on this issue and contribute on this project

**Comment by Sathya-reddy1658** [comment]
i would like to work on this

**Comment by harshit340** [comment]
hy, abhir446  can you please assign this issue to me and it will be really helpfull if you mark the LEVEL for this issue

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me
