### ISSUE TITLE
UP-grading the feedback form with more details

### ISSUE THREAD

**Issue by ayush-848** [Priyaaa1/StartConnect-Hub#603]
**Is your feature request related to a problem? Please describe.**
The emojis are not properly given.
I also want to add more details.

**Comment by Priyaaa1** [comment]
@ayush-848 what details do you want to add?

**Comment by ayush-848** [comment]
> @ayush-848 what details do you want to add?

First The emoji will be properly displayed and on clicking submit the emoji will scale up and then down like a sort of animation
Additional Questions:-
How did you hear about us?
What could we do to improve?
What specific services you liked?
(and why)
Any scope for improvement?

**Comment by ayush-848** [comment]
@Priyaaa1 can you assign this to me?
