### ISSUE TITLE
[Feature]: Add guided conversation functionality to Chatbot

### ISSUE THREAD

**Issue by Priyaaa1** [Priyaaa1/StartConnect-Hub#613]
**Is your feature request related to a problem? Please describe.**
When we ask something to the chatbot, it fails to answer most questions. It can only handle questions which is known to it. 

**Describe the solution you'd like**
We can present users with a predefined set of questions or options they can choose from. This improves the conversation and reduces the chances of the chatbot encountering unanswerable questions.

**Comment by MastanSayyad** [comment]
Hey @Priyaaa1 

I would like to work on it, please assign this issue to me

Also could you please assign #609 issue first (if you like it) to make the chatbot more interactive and engaging!!
then **I will add the conversation functionality**!

Like this:

![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/101971980/79155282-171e-49a6-88f1-8645628ab9db)

**Comment by Priyaaa1** [comment]
@MastanSayyad As you have already got 140+ points from my repository and I assigned you #609 too, I can't assign you this task now.
Let other contributors do this task :)

**Comment by MastanSayyad** [comment]
@Priyaaa1 But there is no such limits for technical projects, I have made this thing clearly with sanjay-kv (gssoc maintainer) 
only documentation based projects have limits

**Comment by MastanSayyad** [comment]
![image](https://github.com/user-attachments/assets/bcdfce23-a1bf-4a57-95c4-ff7cd6780c93)


**"Any Coding/Technical Functionality can be added above 150 points"** - Sanjay-kv

**Comment by Priyaaa1** [comment]
@MastanSayyad oh okay, thanks for informing !!
