### ISSUE TITLE
Adding icons to anchor tags in navbar

### ISSUE THREAD

**Issue by harinisayani** [Priyaaa1/StartConnect-Hub#622]
**Is your feature request related to a problem? Please describe.**
I observed that there is no icons beside anchor tags in navbar.

**Describe the solution you'd like**
I want to add them in webpage.

**Additional context**
Please assign me this issue.
Please add GSSOC and level labels

![Screenshot (205)](https://github.com/user-attachments/assets/e49fbd45-474d-477f-9ea2-0bc0c8ad7673)

**Comment by MastanSayyad** [comment]
@harinisayani Assigned! make sure it does not break other nav components! pls make the PR within 2 days!
