### ISSUE TITLE
Fix Navbar Login  hover effect

### ISSUE THREAD

**Issue by KomalSrivastava** [Priyaaa1/StartConnect-Hub#627]
**Is your feature request related to a problem? Please describe.**
In navbar i have seen contact , about etc hover effect is working well but as you point curser to right  the login is not showing correct effect as compaired to the other . So i can fix this .

**Describe the solution you'd like**
The Login hover should be fix.

**Additional context**
@Priyaaa1 Hello Mam , i have raised this issue and wanted to work on this issue . Kindly assign this issue to me and add gssoc and level to it.

**ScreenRecording for better understanding of what am saying:-

https://github.com/user-attachments/assets/b0a5522b-bef6-4483-8e26-8e04deb0f1a3

**Comment by KomalSrivastava** [comment]
@Priyaaa1 Assign me this issue .

**Comment by MastanSayyad** [comment]
@KomalSrivastava Already fixed, pls look for some other issues!
