### ISSUE TITLE
Improving UI for navbar

### ISSUE THREAD

**Issue by Bhattu-Anitha-07** [Priyaaa1/StartConnect-Hub#629]
Hello PR,
Navitems in the navbar upon hover are looking little weird.
Will improve the hover effect for anchor elements inside the navbar.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5121c90-0950-4c6d-8bbd-bd1df53b6c59)

**Comment by Bhattu-Anitha-07** [comment]
@Priyaaa1 
Kindly assign this issue to me.
Will work on this.

**Comment by Bhattu-Anitha-07** [comment]
@Priyaaa1 @rohitroy-github 
Please label the issue accordingly.
Thank you.

**Comment by Priyaaa1** [comment]
@Bhattu-Anitha-07 this has been done somedays ago.

**Comment by Bhattu-Anitha-07** [comment]
@Priyaaa1 
Ok sure.
