### ISSUE TITLE
Adding a Notification

### ISSUE THREAD

**Issue by DevGajjar28** [Priyaaa1/StartConnect-Hub#631]
**Is your feature request related to a problem? Please describe.**
send message form work like it send the user message to owner, after sending a message user don't know that there message was sent or not , so for user i would like to provide a Notification after sending message. 
 
**Describe the solution you'd like**
The feature would be look like this and adding a color schema matching a bg.
![Screenshot 2024-06-29 155622](https://github.com/user-attachments/assets/f09e463b-e9ec-4e77-b6ce-9fa91b059f81)

**Additional context**

**Comment by MastanSayyad** [comment]
@DevGajjar28 where are you planning to implement this feature?

**Comment by DevGajjar28** [comment]
> @DevGajjar28 where are you planning to implement this feature?

contact us form
