### ISSUE TITLE
BUG:-Hovering over FAQ doesn't makes the cursor to pointer

### ISSUE THREAD

**Issue by K-kiran77** [Priyaaa1/StartConnect-Hub#634]
**Describe the bug**
when hovering over the each question of FAQ cursor is not becoming pointer, If we change it to become pointer it will increase the user experience

**To Reproduce**
1. Go to 'FAQ section'
2. Hover over 'FAQ'
3.See issue

**Expected behavior**
On hover over each question of FAQ section makes the cursor to pointer

**Screenshots**

https://github.com/user-attachments/assets/a178ed13-3014-46c7-96a0-2735e16322f6

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
please assign me this issue under GSSOC 2024

**Comment by Priyaaa1** [comment]
@K-kiran77 this issue isn't there in the website
