### ISSUE TITLE
➕Add Dynamic Copyright Year Functionality to Footer

### ISSUE THREAD

**Issue by aslams2020** [Priyaaa1/StartConnect-Hub#638]
hey @Priyaaa1 ,

Here is the feature -

- The current footer of the website does not have a **dynamically updating copyright year**
This can lead to outdated information and inconsistencies across the site.

![image](https://github.com/user-attachments/assets/7588ab27-89cb-404c-9e92-4b859160d2d5)

### Here's what will I do - 
- Add a script to dynamically update the copyright year in the footer to the current year.

Please assign me this issue under GSSoC'24

**Comment by aslams2020** [comment]
@Priyaaa1

**Comment by Priyaaa1** [comment]
@aslams2020 this functionality is already implemented there.
