### ISSUE TITLE
➕Feature:  Adding Diagonal-Transitional Effect to "Each Contributors Card"

### ISSUE THREAD

**Issue by aslams2020** [Priyaaa1/StartConnect-Hub#658]
Hey @Priyaaa1 

I want to suggest a new feature for "Contributors" Page.

I Want **to add a "Diagonal-Transitional" Effect Styling to each card** of the Contributors page. 
Which means On hovering on Every card, The card will display a Transitional Effect

**For ex.  Like this -(I will follow the StarConnect website theme)** 

https://github.com/user-attachments/assets/b70c3c22-fc3f-4397-854f-53a413bf4d60

**Current Contributor Cards -** 

https://github.com/user-attachments/assets/8359b232-4ac5-444f-9298-9f2787cfd630

As you can see, currently the hovering effects are lagging and have no smooth hover effect.

Please Assign me this issue.

**Comment by MastanSayyad** [comment]
@aslams2020 make sure it aligns with the design theme!
