### ISSUE TITLE
FEATURE 🌟: Improve About Us Section on the Home Page

### ISSUE THREAD

**Issue by Tejashri-Taral** [Priyaaa1/StartConnect-Hub#659]
Hey @Priyaaa1 ,
I want to improve about us section on the home Page
****screenshot****
![image](https://github.com/user-attachments/assets/1b5117f4-08df-40af-b1ed-0c40f1ddee1f)

**Are you contributing under any open-source program?**
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by MastanSayyad** [comment]
Assigned! Make sure it works in both light mode and dark mode! @Tejashri-Taral
