### ISSUE TITLE
On hovering to the signup and login button its not visible 

### ISSUE THREAD

**Issue by dwivedishrey** [Priyaaa1/StartConnect-Hub#66]
The UI of signup and login button is not proper on hovering.
![Screenshot 2024-05-12 103502](https://github.com/Priyaaa1/StartConnect-Hub/assets/97790062/5cad0209-95c8-4567-9321-e17b0a2fcff5)
![Screenshot 2024-05-12 103452](https://github.com/Priyaaa1/StartConnect-Hub/assets/97790062/8482a816-b8c3-474c-91e4-9fd4a3bcad20)
Please assign this issue to me.

**Comment by Kadambini30** [comment]
@dwivedishrey hii, can you assign this issue to me?
