### ISSUE TITLE
✨ Add Icons to Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [Priyaaa1/StartConnect-Hub#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Footer
Can you assign me this issue under GSSOC'24 @Priyaaa1 @MastanSayyad 

### Use Case

![IMG_20240802_010001](https://github.com/user-attachments/assets/a51a8843-bf2f-4f6e-95fc-2317a6614df7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@sailaja-adapa Assigned!
