### ISSUE TITLE
✨ Add Icons To Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [Priyaaa1/StartConnect-Hub#669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello Project Admin
I would like to add icons to Navbar
Can you assign me this issue under GSSOC'24 @Priyaaa1 @MastanSayyad 

### Use Case

![IMG_20240802_010014](https://github.com/user-attachments/assets/97faa62a-d480-4b18-a31d-3b446c01b7b1)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
Already assigned to someone else!
