### ISSUE TITLE
✨ Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [Priyaaa1/StartConnect-Hub#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24 @MastanSayyad @Priyaaa1 

### Use Case

It will Enhance User Experience 

### Add ScreenShots

![IMG_20240706_122058](https://github.com/user-attachments/assets/dde7aa00-f11a-4e52-995b-1ac1235d3a8a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
The website already has Feedback page for the rating!
