### ISSUE TITLE
📝[Docs]: Add Installation and Running Instructions to README

### ISSUE THREAD

**Issue by lovelymahor** [Priyaaa1/StartConnect-Hub#671]
**What Docs changes are you proposing?**
I am proposing additions to the README file to include instructions for installing dependencies and running the application locally.

**Why do the documents need this improvement? What is the motivation for this change? How will this change benefit the community?**
The current README lacks guidance for setting up the project, which can be a barrier for new users. Adding these instructions will help users quickly and easily set up the project, improving accessibility and the user experience.

**Describe the solution you'd like**
Add the following sections to the README:

Install dependencies:
npm install
Running the Application:
npm start

**Describe alternatives you've considered**
An alternative was to create a separate INSTALL.md file, but including these instructions directly in the README ensures all essential information is in one place.

**Additional context**
Including these instructions will streamline the onboarding process for new contributors and users, making it easier for them to get started with the project.

@Priyaaa1  I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by MastanSayyad** [comment]
To run the application`npm run dev` command is used. kindly make the correct changes accordingly!
