### ISSUE TITLE
✨[Feature Request]: To option to apply Dark  Theme to the website

### ISSUE THREAD

**Issue by Unnimaya6122004** [Priyaaa1/StartConnect-Hub#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

to apply dark theme / light theme

### Use Case

to apply dark theme / light theme

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
Dark/light theme is already present! @Unnimaya6122004
