### ISSUE TITLE
Improve the nav in mobile view

### ISSUE THREAD

**Issue by dhanushsurendra** [Priyaaa1/StartConnect-Hub#69]
**Is your feature request related to a problem? Please describe.**
The mobile nav is not visually appealing. It can be improved

![Screenshot 2024-05-12 121440](https://github.com/Priyaaa1/StartConnect-Hub/assets/50047808/badf3dbb-a875-4a46-ade0-4fb96d2df956)
..

**Describe the solution you'd like**
A better nav can be added to the page in mobile view which is more interactive

**Additional context**

**Comment by Aditya6112** [comment]
Can I work on this issue?
Assign this to me.
@dhanushsurendra

**Comment by dhanushsurendra** [comment]
@Aditya6112 I'm not the PA. You got the wrong name
