### ISSUE TITLE
✨[Feature Request]:  Moving the google translate feature to Footer section

### ISSUE THREAD

**Issue by Sourabh782** [Priyaaa1/StartConnect-Hub#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The google tranlate feature at top of the page is degrading the view of site. I propose that the language selection feature should be moved to footer seaction, it will improve the view of site

### Use Case

If the language selection feature will be removed from the top, it will improve the overall UI of site.

### Add ScreenShots

![Screenshot 2024-08-05 193515](https://github.com/user-attachments/assets/5937eba8-b30b-48bc-97a1-fed9f73c8360)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@Sourabh782 Yeah it would be great, Much needed!

**Comment by Sourabh782** [comment]
Sure i will work on that
