### ISSUE TITLE
Enhance Hover effect on Navbar and add background color  to Faqs

### ISSUE THREAD

**Issue by Adarsh1630** [Priyaaa1/StartConnect-Hub#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

when i hovering in navbar element like login so in which hover fix like smooth and give coloring on this element

### Use Case

just to hover on it make intereractive to user

### Add ScreenShots

![PR1](https://github.com/user-attachments/assets/c169c508-87c9-4d81-b6e7-a3e85a37dafa)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
I think the navbar looks good the way it is! pls look for some other issues!
