### ISSUE TITLE
✨[Feature Request]: Add proper message when o results found for blogs in blogs page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Priyaaa1/StartConnect-Hub#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Current when searching blogs, If there is no results, it does not show any kind proper message.

![image](https://github.com/user-attachments/assets/c10798ea-4a45-4e79-a075-430fef61e26e)

### Use Case

So we can display user friendly messages in this scenarios

![image](https://github.com/user-attachments/assets/5b4eab3f-9f87-473f-908c-472551810db6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@DharshiBalasubramaniyam Great! Assigned to you!
