### ISSUE TITLE
Login, signup and footer styling 

### ISSUE THREAD

**Issue by AlaynaShaheen** [Priyaaa1/StartConnect-Hub#7]
I am a contributor in GSSoC' 24. I can solve this issue by add styling to login, signup and footer using CSS. Also I can enchance the UI by adding Navbar to all the pages so that it would be easier for user navigation. Please assign this task to me under GSSoC'24,

**Comment by Shyambarua** [comment]
Assign this issue to me.
As a full Stack Developer and 1 Year experience I can Write optimized code and Make it responsive.

**Comment by nishant0708** [comment]
hey @AlaynaShaheen  i can fic this

**Comment by Abhinavagarwa** [comment]
can u assign me this project under gssoc'24

**Comment by curecode11** [comment]
I have worked upon similar issues earlier , so I can work upon the overall styling and feel of the login, signup and overall landing page .
I am requesting you to assign this task to me. 
![image](https://github.com/curecode11/LoginForm/assets/118065498/6358848e-c9ea-4bc3-955c-09ce3bdc146b) ![image](https://github.com/curecode11/LoginForm/assets/118065498/0943c490-a168-42de-b7cc-8bb95c745071)
