### ISSUE TITLE
Bug in Contributors Data Fetching in Contributors Page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Priyaaa1/StartConnect-Hub#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @Priyaaa1 and @MastanSayyad 

In the contributors page the data of the total contributors is not showing correctly, it only shows the contributors more than one or two contributions of contributors the only limit is 30

![image](https://github.com/user-attachments/assets/4acd0487-40dd-44f5-98bc-78507dcccf1b)

![image](https://github.com/user-attachments/assets/16488faa-eb4c-4ffa-9a9d-ccec071399fd)

### Expected behavior

N/A

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@RadhikaMalpani1702 Assigned, also in sign up page you didn't fix dark mode issue so make sure you fix it
