### ISSUE TITLE
✨[Feature Request]: Updating CSS for Vision and Mission page

### ISSUE THREAD

**Issue by srilekha279** [Priyaaa1/StartConnect-Hub#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhance the design of the Vision and Mission page by updating the CSS for better user visibility.

### Use Case

 Updating the CSS for the Vision and Mission page will enhance the user experience by making the page visually appealing and easier to navigate. This is particularly important for new visitors who are learning about our organization’s goals and values for the first time.

### Benefits

Enhanced User Experience
- A modern and responsive design will make the page more engaging for users.

### Add ScreenShots

![Screenshot (917)](https://github.com/user-attachments/assets/faa104c2-8e09-48bf-ada5-589e03f626fa)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
I don't think there is any need of CSS changes, but you can reduce the gaps between them and please add some Visual Images to look more engaging!

**Comment by MastanSayyad** [comment]
I will ad the levels after seeing the changes

**Comment by srilekha279** [comment]
@MastanSayyad 
Please add level to this.
