### ISSUE TITLE
Add Icons to Navbar Links for Enhanced User Experience

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Priyaaa1/StartConnect-Hub#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MastanSayyad and @Priyaaa1 

I would like to add icons to each link in the navigation bar.
These icons will help users quickly see and understand what each section is about.

like this 

![image](https://github.com/user-attachments/assets/5f0d2e09-c27b-4fb0-bc17-c5a1c1c05e9b)

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@RadhikaMalpani1702 Great but please add white Icons just like footer links icons!

**Comment by RadhikaMalpani1702** [comment]
@MastanSayyad Sure
