### ISSUE TITLE
NOT GOOD About section for Tablet size 768px

### ISSUE THREAD

**Issue by Utsavladia** [Priyaaa1/StartConnect-Hub#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/5d5c3084-9f63-4b13-a62c-ebe33a361a61)

### Use Case

This should be fixed to have better readability on all screen 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
fix the responsiveness in 786px only
