### ISSUE TITLE
🐞[Bug]: About us page is not responsive

### ISSUE THREAD

**Issue by Tejashri-Taral** [Priyaaa1/StartConnect-Hub#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @MastanSayyad and @Priyaaa1 ,
About us page is not responsive
I want to make it responsive for all screen sizes
Please assign it to me.

### Expected behavior

 "About Us" page should offer a smooth and user-friendly experience across all screen sizes

### Add ScreenShots

![WhatsApp Image 2024-08-10 at 01 11 09_5ddb07be](https://github.com/user-attachments/assets/9b53a532-ebef-4c50-aea2-3d776c1853e5)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@Tejashri-Taral make it responsive except 768px
