### ISSUE TITLE
Feature🌟: Upgrade the Current "Services" Page 

### ISSUE THREAD

**Issue by aslams2020** [Priyaaa1/StartConnect-Hub#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Priyaaa1 @MastanSayyad 

i Want to upgrade the current our services page by adding more functionalities to it 

- Updating the Alignments 
- Adding Animated images and gifs
- making it responsive for all screen sizes 
- Make sure it follows the website theme
- Adding more comprehensive info to the Page's sections 
-

Also currently in dark mode, the text is not readable 

Current : 

https://github.com/user-attachments/assets/9ae1ef88-9461-4725-b57a-1aa347a712eb

Please asssing me this issue 

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by aslams2020** [comment]
@MastanSayyad Please assign me, i want to work on this

**Comment by MastanSayyad** [comment]
@aslams2020 pls finish it quickly

**Comment by aslams2020** [comment]
@MastanSayyad doing it asap!
