### ISSUE TITLE
The website icon on navbar page should be connected to homepage

### ISSUE THREAD

**Issue by Apoorva-Rajput** [Priyaaa1/StartConnect-Hub#74]
**The issue**
When a user navigates to different pages in the website , they should be able to come back to home page in a single click for better experience .

**Solution** 
We can connect the website icon to homepage , so that when user need to jump to homepage they can just do it by clicking icon .

@Priyaaa1 kindly assign me this issue as a part of GSSoC'24 . And suggest any changes if required .

**Comment by SanaAzeem512** [comment]
please assign this issue to me

**Comment by amit429** [comment]
hey i am a GSSOC'24 contributor , can you assign me this issue so i can work on it under the GSSOC'24 tag

**Comment by sdass1918** [comment]
Hey please assign this issue to me!
I want to contribute to this project as it seems to be very attractive and creative.

**Comment by himadeepthi1** [comment]
Hello ! @Priyaaa1 ,I'm a GSSOC'24 contributor and I would like to work on this issue

**Comment by Monalisha-Roy** [comment]
hey @Priyaaa1! please assign this issue to me. I can finish this task quickly and perfectly

**Comment by Apoorva-Rajput** [comment]
Closing the issue since it has been already resolved .
