### ISSUE TITLE
Enhancement of Contact Us section UI

### ISSUE THREAD

**Issue by Prithwi32** [Priyaaa1/StartConnect-Hub#8]
To properly align all components and improve styling of Contact Us Section

**Comment by Prithwi32** [comment]
@Priyaaa1 Please could you assign me this issue under GSSoC'24

**Comment by Anshydv18** [comment]
To properly align all components and improve styling of Contact Us Section

**Comment by Anou25** [comment]
Hi, I want to work on this issue please assign it to me, I will try to make it more appealing and improve the UI in better way.
