### ISSUE TITLE
Explore More Button Feature

### ISSUE THREAD

**Issue by lakshyajn** [Priyaaa1/StartConnect-Hub#80]
**Is your feature request related to a problem? Please describe.**
The Explore more feature is not working yet.

**Describe the solution you'd like**
I would like to add a feature and UI of a screen that will be containing accounts of top startups, like in linkedin format

**Additional context**
It would be great to have this feature, as people could explore the connections they want

**Comment by SanaAzeem512** [comment]
hello.
please assign this issue to me under GSSOC24
