### ISSUE TITLE
ADD LOGIN FEATURE INTEGRATED WITH GOOGLE 

### ISSUE THREAD

**Issue by MuthuvelA** [Priyaaa1/StartConnect-Hub#84]
Hey @Priyaaa1  I am Muthuvel and I have prior experience of working with MERN stack. I would like to work on this issue. could you assign this issue to me with GSSOC'24 label.

Ok, now talking about Adding google authentication:-
The integration of Google Sign-In functionality was achieved using the GoogleLogin component from the @react-oauth/google library.
Upon successful authentication with Google, the received credentials are decoded using the jwt-decode library to extract relevant user information.
Error handling mechanisms are in place to gracefully manage scenarios where Google authentication fails or the received credentials are invalid.
The user interface (UI) of the GitHub feature column was updated to include visually appealing and intuitive buttons for Google Sign-In and Sign-Up actions, ensuring a seamless user experience.
Using Google OAuth

This feature will make the user easy to login.

I have read the code of conduct and expecting positive response. Thank you

**Comment by Priyaaa1** [comment]
@MuthuvelA Kindly make changes with 2-3 days

**Comment by its-AkshatJain** [comment]
Hello @Priyaaa1 ,
I am Akshat , a GSSOC Contributor.
Please assign me this task i can add login feature integrated with google.

**Comment by MuthuvelA** [comment]
> Hello @Priyaaa1 , I am Akshat , a GSSOC Contributor. Please assign me this task i can add login feature integrated with google.

I am currently working on it and will finish within today

**Comment by MuthuvelA** [comment]
Hello @Priyaaa1 I have completed the task and raised a pull request

**Comment by n14rishitha** [comment]
Hello @Priyaaa1 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by ManishBirthlia** [comment]
I already solved this issue please assign me this and check my pull request and it will merge for sure.... check this pull request #295

**Comment by Priyaaa1** [comment]
@MuthuvelA there is no PR raised by you

**Comment by MuthuvelA** [comment]
I have raised PR ans you merged it
