### ISSUE TITLE
Mobile Layout Issue: Lack of Media Queries for Responsive Design

### ISSUE THREAD

**Issue by Khizarshah01** [Priyaaa1/StartConnect-Hub#9]
Issue Description:
The website's mobile layout appears distorted and doesn't adjust properly to different screen sizes. Upon inspecting the code, it seems that there are no media queries implemented to ensure proper responsiveness on mobile devices.

![Screenshot_20240510_002313.jpg](https://github.com/Priyaaa1/StartConnect-Hub/assets/109973520/0a9638eb-505c-4bb8-9cd4-428141bab289)

**Comment by Khizarshah01** [comment]
@Priyaaa1 could you assign me this issue under GSSoC'24

**Comment by Harsha19-08** [comment]
can u assign the issue under GSSOC'2024

**Comment by harshit340** [comment]
Hy @Khizarshah01 can you assign this issue to me I have a good knowledge in media query and worked with it my last project

**Comment by Khizarshah01** [comment]
@Priyaaa1 Thanks for assigning me this issue! I'll get started on it right away.

**Comment by Khizarshah01** [comment]
issue resolved with the addition of media queries. Closing the issue now.

**Comment by Khizarshah01** [comment]
Someone added a new feature to the homepage but didn't make it mobile responsive. I'll try to fix this error by reopening the existing issue.

**Comment by Khizarshah01** [comment]
issue resolved.Closing the issue now.
