### ISSUE TITLE
Adding hover effect to the images on the Testimonials carousel

### ISSUE THREAD

**Issue by Rakshit-gen** [Priyaaa1/StartConnect-Hub#98]
**Is your feature request related to a problem? Please describe.**
The images in the testimonial carousel seem really simple we can add a hover effect on them to make them look better.

**Additional context**
![image](https://github.com/Priyaaa1/StartConnect-Hub/assets/64471316/fcacfb58-e9a1-4e9b-9b7e-21283df630cc)

**Comment by Rakshit-gen** [comment]
Please assign this issue to me!

**Comment by Deepthi-Ramineni** [comment]
I would like to work on it. Can you assign it to me...???
