### ISSUE TITLE
Hover effect on testimonials

### ISSUE THREAD

**Issue by Chelseasingla1** [Priyaaa1/StartConnect-Hub#99]
**Is your feature request related to a problem? Please describe.**
No hover effect on images or testimonials

**Describe the solution you'd like**
i would like to add some change to make it look more interactive by adding hover effect on images in testimonials section.

**Additional context**
please assign me this issue under GSSoC'24.

**Comment by reshamsai150** [comment]
Adding a hover effect for testimonials can make the user experience better assign this issue to me @Priyaaa1
